### ISSUE TITLE
Remove gsuite requirement from project factory

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-project-factory#11]
Currently, the G Suite functionality causes a lot of pain and complexity in set up. We should make it a totally optional component (meaning you can use the project factory without ever installing the G Suite provider).

New architecture:
- outer wrapper module references inner module
- gsuite add on handles group creation and service account group management, passes through to inner module
- inner module which holds all the non-gsuite components from current module

**Comment by adrienthebo** [comment]
Addressed in Project Factory v1.0.0.
