### ISSUE TITLE
What happened with the disable_services_on_destroy variable?

### ISSUE THREAD

**Issue by amardomingo** [terraform-google-modules/terraform-google-project-factory#124]
The variable disable_services_on_destroy use to be added to the core module call in the /main.tf file. However, at some point it seems it was removed (commit 373875477871aa52a65079223174e5e16eec1779 )

Is this intended? If so, it is possible to regain that funcionality somehow?

**Comment by aaron-lane** [comment]
Hi @amardomingo.

Thank you for catching this issue. It is not intended and will be rectified.

**Comment by amardomingo** [comment]
Great! Thank you :-)
