### ISSUE TITLE
Provide ability to delete default VPC gateway route on project creation

### ISSUE THREAD

**Issue by bmenasha** [terraform-google-modules/terraform-google-project-factory#135]
Similar to how we have functionality to delete the default GCE service account, can we add an option to delete default VPC gateway route on the project VPC? 

The customer is asking for this feature as they wish to intercept all egress traffic with a security device. They will create their own route for this interception and routing of traffic from the security device to the gateway.  

Thanks!

**Comment by morgante** [comment]
The project factory deletes the default network, so I'm not sure which route this is referring to?

When creating a custom network, does this route still get created?

**Comment by bmenasha** [comment]
thanks for the quick reply Morgante. yes it does when creating a custom network.  perhaps that's where this feature should exist (https://github.com/terraform-google-modules/terraform-google-network) .   So one can delete the vpc after project creation (which is default behavior of the project factory), then add ability to delete default internet gateway route to  https://github.com/terraform-google-modules/terraform-google-network  when creating a new vpc for the project.  i can create an issue there. 
thanks

**Comment by morgante** [comment]
Thanks, closing this so you can open an issue there.
