### ISSUE TITLE
broken link in readme for test_preconditions.py

### ISSUE THREAD

**Issue by ibenrodriguez** [terraform-google-modules/terraform-google-project-factory#136]
The link contained in the "Verifying Setup" section of the readme.md file is wrong.  https://github.com/terraform-google-modules/terraform-google-project-factory#verifying-setup

A preconditions checker script is included to verify that all preconditions are met before the Project Factory runs. The script will run automatically if the script dependencies (Python, "google-auth", and "google-api-python-client") are available at runtime. If the dependencies are not met, the precondition checking step will be skipped.

The precondition checker script can be directly invoked before running the project factory:

./scripts/preconditions/preconditions.py \
  --credentials_path "./credentials.json" \
  --billing_account 000000-000000-000000 \
  --org_id 000000000000 \
  --folder_id 000000000000 \
  --shared_vpc 'shared-vpc-host-ed64'

The link in the readme should point to the actual file location as such: https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/test/scripts/preconditions/test_preconditions.py

But instead it now shows:  https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/scripts/preconditions/preconditions.py

I will create a pull request to fix the readme file.

**Comment by morgante** [comment]
Thanks for the catch, looking forward to PR.

**Comment by adrienthebo** [comment]
Noting for posterity that the preconditions script is located at `modules/core_project_factory/scripts/preconditions/preconditions.py` as of 7112228.
