### ISSUE TITLE
Provide ability to choose the region of the bucket

### ISSUE THREAD

**Issue by sdouche** [terraform-google-modules/terraform-google-project-factory#167]
Hi,
the module creates the bucket in the US (`bucket_name` and `bucket_project` options), it would be cool to have the ability to choose the region.

Thanks

**Comment by morgante** [comment]
Fixed by #170

**Comment by sdouche** [comment]
Hi,
Why the variable is only added on the module and not on top?

Regards.

**Comment by morgante** [comment]
You're right, we also need to have this in the top-level module.

**Comment by morgante** [comment]
Fixed by #207
