### ISSUE TITLE
Script not found error when deleting default service account

### ISSUE THREAD

**Issue by ramzimaalej** [terraform-google-modules/terraform-google-project-factory#185]
I'm trying to use this module to create a gcp project but it fails when it tries to delete the default service account. I'm using google cloud build as a ci tool.

`
Finished Step #3
Step #3: 
Step #3: 
Step #3: above and apply again to incrementally change your infrastructure.
Step #3: any resources that successfully completed. Please address the error
Step #3: Instead, your Terraform state file has been partially updated with
Step #3: Terraform does not automatically rollback in the face of errors.
Step #3: 
Step #3: 
Step #3: * module.project.module.project-factory.null_resource.delete_default_compute_service_account: Error running command '/workspace/environments/dev/.terraform/modules/112ba820419105134cc3b145beda68a6/scripts/delete-service-account.sh veamly-platform-dev 1071075091675-compute@developer.gserviceaccount.com ': exit status 127. Output: /bin/sh: /workspace/environments/dev/.terraform/modules/112ba820419105134cc3b145beda68a6/scripts/delete-service-account.sh: not found
Step #3: 
Step #3: 1 error(s) occurred:
`

**Comment by ramzimaalej** [comment]
not sure why it failed, but it works using this docker image: https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/terraform

**Comment by morgante** [comment]
Perhaps the Cloud Build image you used didn't include bash, closing since the other image worked.
