### ISSUE TITLE
Permissions required by setup-sa.sh not documented

### ISSUE THREAD

**Issue by chrislovecnm** [terraform-google-modules/terraform-google-project-factory#192]
I have a user that does not have the correct permissions to run the setup-sa.sh script.  The documentation does not tell me what permissions I need in order to run this scripts.  Here is my error:

```console
 $ ./helpers/setup-sa.sh my-org my-project
Verifying organization...
Verifying project...
Skipping billing account verification... (parameter not passed)
Creating Seed Service Account...
Created service account [project-factory-6999].
Downloading key to credentials.json...
Applying permissions for org org-number and project chlove-baseproject...
ERROR: (gcloud.organizations.add-iam-policy-binding) User [chlove@google.com] does not have permission to access organization [org-number:getIamPolicy] (or it may not exist): The caller does not have permission
```

I removed org number and project id for security sake.

What permissions does the user need to run the setup-sa.sh script?

**Comment by morgante** [comment]
I believe Organization Admin should be sufficient, we should add this under the [script helper](https://github.com/terraform-google-modules/terraform-google-project-factory#script-helper) documentation.

**Comment by chrislovecnm** [comment]
Many ops people will not have .org admin. Do we know the perms?

**Comment by morgante** [comment]
I believe the *org* permissions required are:

- resourcemanager.organizations.get
- resourcemanager.organizations.getIamPolicy
- resourcemanager.organizations.setIamPolicy

Additional perms are required on the seed project.

**Comment by aaron-lane** [comment]
@chrislovecnm can you please confirm if these permissions were sufficient to unblock your user?

**Comment by chrislovecnm** [comment]
Have not had a chance to validate
