### ISSUE TITLE
Can't specify folder_id.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [terraform-google-modules/terraform-google-project-factory#195]
```
module "host-project" {
  source            = "terraform-google-modules/project-factory/google"
  random_project_id = true
  name              = "${local.host_project_name}"
  billing_account   = "${var.billing_account}"
  auto_create_network = false
  group_name = "${var.sysadmingroup}"
  labels = "${var.labels}"
  folder_id = "${var.folder_id}"
  # org_id = "${var.org_id}
}
```

When both org_id and folder_id are specified:
* google_project.main: 'org_id' and 'folder_id' cannot be both set.

When org_id is not specified:
 module "host-project": missing required argument "org_id"

How can I create a project in a folder?

**Comment by iniinikoski** [comment]
Hi @mikhail-khodorovskiy,

Interesting... I'm able to create projects into folder - no error like yours happening...

Using the latest factory with latest TF version (0.11.14)...

**Comment by mikhail-khodorovskiy** [comment]
I was also passing domain.  When I stopped doing that, the error went away.

**Comment by aaron-lane** [comment]
@mikhail-khodorovskiy can you please confirm which version of the module you are using?

**Comment by ingwarr** [comment]
> ```
> module "host-project" {
>   source            = "terraform-google-modules/project-factory/google"
>   random_project_id = true
>   name              = "${local.host_project_name}"
>   billing_account   = "${var.billing_account}"
>   auto_create_network = false
>   group_name = "${var.sysadmingroup}"
>   labels = "${var.labels}"
>   folder_id = "${var.folder_id}"
>   # org_id = "${var.org_id}
> }
> ```
> 
> When both org_id and folder_id are specified:
> 
> * google_project.main: 'org_id' and 'folder_id' cannot be both set.
> 
> When org_id is not specified:
> module "host-project": missing required argument "org_id"
> 
> How can I create a project in a folder?

Could you please provide me with the path to reproduce this issue.  I can't reproduce it in my environment. All looking good and I can create a project in a folder and without folder.

**Comment by neodani** [comment]
Same error
I'm using **Terraform v0.11.14** and this version module **2.4.1**

Any idea how to solve? if I have to increase terraform version or module version? Thanks!

```
module "project-1" {
  source            = "terraform-google-modules/project-factory/google"
  version           = "2.4.1"
  
  name              = "${var.host_project_id}"
  credentials_path  = "${var.credentials_file_path}"
  random_project_id = "false"

  activate_apis = [
    "compute.googleapis.com",
    "cloudbilling.googleapis.com",
    "storage-api.googleapis.com",
    "sourcerepo.googleapis.com",
    "monitoring.googleapis.com",
    "logging.googleapis.com"
  ]

  folder_id              = "${var.folder_ops_networking}"
  org_id              = "${var.organization_id}"
  auto_create_network = "false"
  billing_account     = "${var.billing_account_id}"
}
```


1 error occurred:
	* module.project-1.module.project-factory.google_project.main: 1 error occurred:
	* google_project.main: 'org_id' and 'folder_id' cannot be both set.

**Comment by morgante** [comment]
@neodani Can you try using the latest module version with Terraform 0.12? Specifying a folder works for me:

```
module "project-prod-morgantep" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 3.0"

  name              = "clf-morgantep-prod2"
  folder_id         = google_folder.prod.name
  org_id            = var.organization_id

  billing_account   = var.billing_account

  activate_apis = [
    "compute.googleapis.com",
    "container.googleapis.com",
  ]
}
```

Terraform version info:
```
Terraform v0.12.5
+ provider.google v2.11.0
+ provider.google-beta v2.11.0
+ provider.null v2.1.2
+ provider.random v2.1.2
```
