### ISSUE TITLE
disable_dependent_services

### ISSUE THREAD

**Issue by shyamgovardhan** [terraform-google-modules/terraform-google-project-factory#196]
**Error: module.host-project.module.project-factory.google_project_service.project_services: : invalid or unknown key: disable_dependent_services**

**cft.tfvars**
organization_id = "12345678790"
billing_account = "AAAAA-BBBBB-CCCCC"
credentials_path = "demo_credentials_20190430131031.json"

**terraform.tfvars** 
host_project_name = "shared-vpc-host-090519"
network_name = "shared-vpc-net-090509"

terraform -v
Terraform v0.11.13
+ provider.google v1.20.0
+ provider.google-beta v1.20.0
+ provider.null v2.1.2
+ provider.random v2.1.2

**Comment by shyamgovardhan** [comment]
There error is produced when terraform plan is executed from the shared_vpc folder.

https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/examples/shared_vpc

terraform plan -var-file=cft.tfvars

**Comment by aaron-lane** [comment]
@ingwarr please take this issue.

**Comment by ingwarr** [comment]
I've took it

**Comment by morgante** [comment]
Hi @shyamgovardhan,

It looks like you're using a very old version of the Google Provider (1.2). Can you try upgrading to the 2.1 version of the provider and seeing if your issue is fixed?

**Comment by shyamgovardhan** [comment]
Thanks Morgante, It worked after changing the provider version. Could you change the provider version in the examples folder. 

provider "google" {
  credentials = "${file(local.credentials_file_path)}"
  version     = "~> 2.1"
}

provider "google-beta" {
  credentials = "${file(local.credentials_file_path)}"
  version     = "~> 2.1"
}

**Comment by ingwarr** [comment]
I've changed it https://github.com/terraform-google-modules/terraform-google-project-factory/pull/198
