### ISSUE TITLE
Need to be authoritative on activate_apis

### ISSUE THREAD

**Issue by jcejohnson** [terraform-google-modules/terraform-google-project-factory#202]
I need to be able to tell terraform-google-modules/project-factory/google to use terraform's google_project_services resource (instead of google_project_service).

I propose a new attribute `apis_authority` for use in modules/core_project_factory/main.tf:

    resource "google_project_service" "project_services" {
      count = "${ apis_authority == "true" ? 0 : length(var.activate_apis)}"
      ...

    resource "google_project_services" "project_services_authority" {
      count = "${ apis_authority == "true" ? 1 : 0}"
      ...

I can implement a workaround in our code by not passing activate_apis to the module but I see that the module is treating container.googleapis.com as a special case and I'm concerned about future special cases.

Typical usage:

    module "my-project" {
      source = "terraform-google-modules/project-factory/google"
      apis_authority = true
      activate_apis = [ ... ]
      ...

**Comment by morgante** [comment]
This is now available.
