### ISSUE TITLE
gsuite_enabled should not require credentials_path

### ISSUE THREAD

**Issue by bbrouwer** [terraform-google-modules/terraform-google-project-factory#205]
The `credentials_path` for the `gsuite_enabled` module should not be required since it is only being passed to the core_project_factory doesn't require it.

**Comment by morgante** [comment]
Yes, good catch. PR welcome. :)

**Comment by bbrouwer** [comment]
As I make progress with this, I'm running into more issues. If I don't provide the `credentials_path`, I get the following error:
```
WARNING:google.auth._default:No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
Traceback (most recent call last):
  File "./preconditions.py", line 458, in <module>
    retcode = main(sys.argv)
  File "./preconditions.py", line 440, in main
    results.append(validator.validate(credentials))
  File "./preconditions.py", line 247, in validate
    parent = "projects/" + self.project_id
TypeError: must be str, not NoneType
```

The reason I am going down this path is that we currently don't have all of our Terraform setup with CI/CD and auditors want to know who is actually making changes to the GCP environment; meaning they want to see my name in the audit logs, and not some service account. Is this module really designed only for CD, in which case, why make `credentials_path` optional? Is it unreasonable to see my name in the audit logs?

**Comment by morgante** [comment]
> Is this module really designed only for CD, in which case, why make credentials_path optional?

We definitely don't want to make `credentials_path` required, because we would like to support two key scenarios:

1. Running in environments where identity is implicit (ex. Cloud Build or GCE VM)
2. Being able to apply changes locally using user credentials

Could you open a separate bug about the preconditions script issue?
