### ISSUE TITLE
Fail to move an org-level project to folder-level

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-project-factory#226]
When creating a project with only `org_id` set, and later trying to set `folder_id` to move that project under a folder, we get the following error:
```
1 error occurred:
        * module.audit-project.module.project-factory.google_project.main: 1 error occurred:
        * google_project.main: 'org_id' and 'folder_id' cannot be both set.
```

The issue stems from the provider but the solution provided in the GitHub [issue](https://github.com/terraform-providers/terraform-provider-google/issues/1701) doesn't work for PF.

**Comment by morgante** [comment]
Given this is an upstream provider issue, I don't think there's much we can do in the module to fix it. Now that 0.12 is out, let's try to fix it on the provider (please open a new issue there).
