### ISSUE TITLE
Add test suite for app_engine submodule

### ISSUE THREAD

**Issue by aaron-lane** [terraform-google-modules/terraform-google-project-factory#227]
This test suite should leverage the `app_engine` example module.

**Comment by aaron-lane** [comment]
- [ ] `examples/app_engine/main.tf` should be updated to create a project with an instance of `../..` and then pass the project ID to an instance of `../../modules/app_engine`.
- [ ] The G Suite provider should be removed from the example configuration.
- [ ] The hard-coded reference to the service account key should be removed from the example configuration.
- [ ] `location_id` should be hard-coded
- [ ] `auth_domain` should be hard-coded if it does not need to be a real value
- [ ] `serving_status` should be hard-coded to `"SERVING"`
- [ ] `feature_settings` should be hard-coded to `[{ split_health_checks = true }]`
- [ ] The app_engine module instance in the full fixture configuration should be removed
- [ ] `test/integration/full/controls/app-engine.rb` should be moved to the new suite
- [ ] The new test suite should be included in `build/int.cloudbuild.yaml`

**Comment by bharathkkb** [comment]
@aaron-lane I can pick this up if not assigned yet.

**Comment by aaron-lane** [comment]
Sure thing!
