### ISSUE TITLE
Attempting to remove non existent default network

### ISSUE THREAD

**Issue by jmenon-mwp** [terraform-google-modules/terraform-google-project-factory#249]
When trying to create a project using the project factory module, it tries to remove the default network and fails, there by causing the 'terraform apply' to fail half way through. This is because the organizational policy for 'do not create default network' is on in the Org where I tested this.

**Comment by jmenon-mwp** [comment]
Closing issue, was just the lack of RTFM

**Comment by morgante** [comment]
@jmenon-mwp We still probably want to fix this case actually.

**Comment by anagas** [comment]
Hello @jmenon-mwp @morgante  What is the solution?

**Comment by morgante** [comment]
@anagas We haven't fixed this in the core module yet, but you can workaround this by setting `auto_create_network` to true.

**Comment by anagas** [comment]
@morgante thanks!

**Comment by morgante** [comment]
Can you share the error logs for what you get? As far as I can tell from [the code](https://github.com/terraform-providers/terraform-provider-google/blob/bcf010a9581fc5a91cbde7e8d7c8d41b45b58777/google/resource_google_project.go#L278), there shouldn't be an error raised if you attempt to delete a non-existent default network.

**Comment by morgante** [comment]
Looks like you need to use v2.13.0 of the provider: https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#2130-august-15-2019

> project: ignore errors when deleting a default network that doesn't exist (#4137)
