### ISSUE TITLE
Optimization of lint test for terraform fmt

### ISSUE THREAD

**Issue by ingwarr** [terraform-google-modules/terraform-google-project-factory#250]
Current construction in lint tests for  terraform fmt is not optimal, because of too many bash calls in the pipe I suggest minimalistic and enough construction for it:
`find . -type f -name "*.tf" -exec terraform fmt -diff -check=true -write=false {} \;`
instead of:
  echo "Running terraform fmt"
  find_files . -name "*.tf" -print0 \
    | compat_xargs -0 -n1 dirname \
    | sort -u \
    | compat_xargs -t -n1 terraform fmt -diff -check=true -write=false

**Comment by aaron-lane** [comment]
This was made obsolete by the new developer tools image.
