### ISSUE TITLE
Precondition is not working on windows machine

### ISSUE THREAD

**Issue by anagas** [terraform-google-modules/terraform-google-project-factory#254]
Hello

I tried to run this module but it failed with this error message:

Error: Error running command '    ./terraform/modules/service_project/terraform-google-modules-terraform-google-project-
factory-2d181ab/modules/core_project_factory/scripts/preconditions.sh \
    --credentials_path 'C:/Users/xxx/Documents/xx/TestingTerraform/create_projects_with_peering/account.json'
\
    --billing_account 'xx' \
    --org_id 'xx' \
    --folder_id 'folders/xx' \
    --shared_vpc ''
': exit status 1. Output: '.terraform' is not recognized as an internal or external command,
operable program or batch file.

I looked at the configuration and found out that the path in local-exec for preconditions is only for linux. I changed the path to the preconditions.sh then it worked.

Regards,

**Comment by morgante** [comment]
What was the update you made to get it working?

**Comment by anagas** [comment]
Hello morgante

i changed the main.tf in core_prohects_factory.

  provisioner "local-exec" {
    command = <<EOD
    C:\Users\xx\Documents\xx\xx\TestingTerraform\create_projects_with_peering\.terraform\modules\service_project\terraform-google-modules-terraform-google-project-factory-2d181ab\modules\core_project_factory\scripts\preconditions.sh \
    --credentials_path '${var.credentials_path}' \
    --billing_account '${var.billing_account}' \
    --org_id '${var.org_id}' \
    --folder_id '${var.folder_id}' \
    --shared_vpc '${var.shared_vpc}'
EOD

**Comment by anagas** [comment]
Hello morgante

Its not the only path which is not working. Every path that is received from ${path.module} is not working in windows.

Regards,

Ahmet

**Comment by morgante** [comment]
Could you open an upstream issue? This seems like a Terraform code bug.

**Comment by anagas** [comment]
I opend a ticket on terraform.
