### ISSUE TITLE
Error msg when running toolkit on Windows

### ISSUE THREAD

**Issue by jeffling-google** [terraform-google-modules/terraform-google-project-factory#265]
when i ran it on Windows, I got the following error: 

module.service_project.module.project-factory.null_resource.preconditions (local-exec): Executing: ["cmd" "/C" ".terraform/modules/service_project/modules/core_project_factory/scripts/preconditions.sh \\\r\n    --credentials_path '' \\\r\n    --impersonate_service_account '' \\\r\n    --billing_account 'xxxxx' \\\r\n    --org_id 'xxxx' \\\r\n    --folder_id 'folders/xxxx' \\\r\n    --shared_vpc 'xxx'\r\n"]
module.service_project.module.project-factory.null_resource.preconditions (local-exec): '.terraform' is not recognized as an internal or external command,
module.service_project.module.project-factory.null_resource.preconditions (local-exec): operable program or batch file.

Error: Error running command '.terraform/modules/service_project/modules/core_project_factory/scripts/preconditions.sh \
    --credentials_path '' \
    --impersonate_service_account '' \
    --billing_account 'xxxx \
    --org_id 'xxxx' \
    --folder_id 'folders/xxxx' \
    --shared_vpc 'xxxx'
': exit status 1. Output: '.terraform' is not recognized as an internal or external command,
operable program or batch file.

**Comment by thefirstofthe300** [comment]
Yeah. The issue here is that Windows is trying to run the shell script as a batch file. The local-exec provisioner needs to be updated to either not run while on Windows or we need a batch file to do everything in the preconditions and use that on Windows.

Or we need to document that the module is not supported if being run outside of a bash/zsh environment.

**Comment by morgante** [comment]
Agreed. I think the best immediate fix is to explain that this module isn't supported on Windows/outside of a bash environment.
