### ISSUE TITLE
Remove google_project_services

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-project-factory#279]
The `google_project_services` resource has been [deprecated](https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#2170-october-08-2019).

We need to remove it and the associated `apis_authority` input option (added in #202). Everyone will need to use the `google_project_service` resource.

**Comment by goobysnack** [comment]
Is there anyway we can leave it in post 3.0, as a known legacy resource?  Changing this might create a disruptive race condition in the state file for active services.  Additionally, the method that the state is stored is numerical, and when one service is removed from the tf config, the state is reorderd, and the apply errors out.

**Comment by morgante** [comment]
The service is going to be removed in 3.0, so unfortunately we'll be unable to retain it.

However, as described in #282, we will do work to switch to `for_each` before removing this resource.

**Comment by goobysnack** [comment]
> The service is going to be removed in 3.0, so unfortunately we'll be unable to retain it.
> 
> However, as described in #282, we will do work to switch to `for_each` before removing this resource.

Just so I'm clear - we can pin the google provider to <3.0.  Also, since we haven't migrated from Terraform .11 to .12 yet, we can't use `for_each` correct?

TIA

**Comment by morgante** [comment]
> Just so I'm clear - we can pin the google provider to <3.0. Also, since we haven't migrated from Terraform .11 to .12 yet, we can't use for_each correct?

Correct, you can pin to an old version of the module and provider in your configuration.

I'd strongly consider upgrading to 0.12 and the new provider versions in the future though, as support will continue to grow less.

**Comment by goobysnack** [comment]
On our horizon, just need to find the time and resources :D

**Comment by aaron-lane** [comment]
If the change will be disruptive to active services then we should include a migration script.

**Comment by morgante** [comment]
This has already been released in October: https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/CHANGELOG.md#400---2019-10-21

**Comment by morgante** [comment]
@taylorludwig Nothing to do here, please ignore.
