### ISSUE TITLE
pip3 install needs --user on OS X

### ISSUE THREAD

**Issue by ideasculptor** [terraform-google-modules/terraform-google-project-factory#289]
Native python on OS X will not allow installs to the global python.  All installs must happen with a --user flag.  It would be really nice to enable that in the code.  At the moment, mac users have to manually run the pip3 install command or modify preconditions.sh n order to get the module to run.

I'll send a PR shortly.

**Comment by ideasculptor** [comment]
Adding a variable which gets used as additional params to pip3 in preconditions.sh is easy enough.  I have that branch ready to submit as PR.  

But I suspect most users would actually prefer a boolean flag that just does the right thing when installing on Mac - detecting if the OS is mac, and then setting --user if it is, rather than just forcing the extra param(s) into all pip3 install calls when the extra param is set in the variable, regardless of platform.

If that's preferred, I can implement that, especially if there is code someone can point me to which does OS detection inside terraform.

**Comment by aaron-lane** [comment]
Fixed by #290

**Comment by morgante** [comment]
An alternative approach, as discussed in #290, would be to split the dependency install into a separate `local-exec` which can be (optionally) disabled and pre-installed.

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-project-factory/pull/478
