### ISSUE TITLE
Unable to use variable for value of shared_vpc parameter

### ISSUE THREAD

**Issue by vilmacs** [terraform-google-modules/terraform-google-project-factory#291]
I want to supply the shared vpc host project id as a variable reference: 

  shared_vpc         = "${module.network-services-host.project_id}"

Yet this isn't possible and produces the error: 

  on .terraform/modules/analytics-service-1/modules/core_project_factory/main.tf line 177, in resource "google_compute_shared_vpc_service_project" "shared_vpc_attachment":
 177:   count = var.shared_vpc_enabled ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

The same is true of the shared_vpc_subnets  property..

shared_vpc_subnets = ["${module.production-vpc.subnets_self_links[0]}"]

results in 

  on .terraform/modules/analytics-service-1/modules/core_project_factory/main.tf line 113, in resource "null_resource" "check_if_shared_vpc_subnets_contains_items_with_invalid_name":
 113:   count = length(
 114:     compact(null_resource.shared_vpc_subnet_invalid_name.*.triggers.name),
 115:   ) == 0 ? 0 : 1

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

thanks

**Comment by vilmacs** [comment]
i guess the error message makes it clear what the work around is.
thanks

**Comment by morgante** [comment]
@vilmacs FYI you can also use [Shared VPC](https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/shared_vpc) submodule to solve for this case as it *does* allow referencing a shared VPC.
