### ISSUE TITLE
running the lint test errors out on .gitignore'd files

### ISSUE THREAD

**Issue by ideasculptor** [terraform-google-modules/terraform-google-project-factory#297]
test/source.sh gets generated by the integration tests, but then that file causes the lint test to fail because it lacks the correct headers.  It is listed in test/.gitignore. Remove the file to get tests to pass, but it would be better to just ignore it.

**Comment by morgante** [comment]
Good catch, we should add it to the ignored file: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/build/developer-tools/build/scripts/task_helper_functions.sh#L59

**Comment by ideasculptor** [comment]
Woah, what the heck is that repo?!  Are the terraform-google-modules mostly translations of those CFT templates to terraform code?  I've been looking for examples more significant than those found in the google-cloud-fabric repo which actually string all of the modules together in a coherent way, while building my own reference architecture.  I've only spent a couple of minutes digging through that repo, but could I maybe find the equivalent of that in there?

I wish I'd known about all of this work before I left Google in 2017.  I was bored stiff and underutilized in a satellite office with little potential, so I left, but now here I am doing all of this work for free, instead.  PR submission shortly.

**Comment by morgante** [comment]
> Woah, what the heck is that repo?! Are the terraform-google-modules mostly translations of those CFT templates to terraform code? 

Essentially, yes. They're human-translated/managed but we try to have DM templates and Terraform modules provide similar functionality.

The other key thing in that repo is the developer-tools image which is used for CI builds.

> I've only spent a couple of minutes digging through that repo, but could I maybe find the equivalent of that in there?

Right now, the Fabric repo is probably the best reference. We're hoping to publish some more e2e examples this quarter though.

**Comment by ideasculptor** [comment]
I suspect this doesn't get fixed until a new release of the module happens (or maybe the cft repo needs a release), but it should go away sooner rather than later now that the fix is merged.

**Comment by morgante** [comment]
Specifically, it'll get fixed once the tool image [here](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/build/lint.cloudbuild.yaml#L24) and [here](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/Makefile#L21) are updated to the latest version (`0.4.7`).

**Comment by aaron-lane** [comment]
Fixed by #410.

**Comment by aaron-lane** [comment]
Fixed by #312
