### ISSUE TITLE
Empty list on activate_apis result in error

### ISSUE THREAD

**Issue by JulienOrain** [terraform-google-modules/terraform-google-project-factory#300]
Hi,

First of all, I would like to thank you for this project !

I am currently trying to set up a project for which I do not want any API activated by default.

I set up variables as follow : 
```
variable "activate_apis" {
  description = "Service APIs to enable."
  default = []
}
```

When I run `terraform plan`, I got the following error :

```
Error: Error in function call

  on .terraform/modules/.../terraform-google-modules-terraform-google-project-factory-a1584fe/modules/project_services/outputs.tf line 19, in output "project_id":
  19:   value = element(
  20: 
  21: 
  22: 
    |----------------
    | google_project_service.project_services is object with no attributes

Call to function "element" failed: cannot use element function with an empty
list.
```

If my understanding is ok, the error seems to come from the fact that we tried to loop on an empty list. 

Thanks !

**Comment by morgante** [comment]
Currently I don't think we support the ability to activate no APIs.

Can I ask more about your use case? Even if we made this particular aspect work, it's likely that other module functionality would break if *no* APIs are activated.

**Comment by JulienOrain** [comment]
Got your point !

My use case here is to create a gcp project as an empty shell. I admit that the use case is border line...
However, as it used to work with version `3.*.*` of `terraform-google-project-factory`, I was a bit surprised when the migration to `4.*.*` brought this issue out.

My workaround for now is to activate "compute.googleapis.com" by default.

**Comment by Rycieos** [comment]
This was an artifact of the changes I made here. I agree, it used to work in 3.X. My mistake, I'll open a PR to fix.

**Comment by JulienOrain** [comment]
Thanks guys !
