### ISSUE TITLE
modules only allow single shared_vpc

### ISSUE THREAD

**Issue by ideasculptor** [terraform-google-modules/terraform-google-project-factory#306]
I have a service-project which will need to use the network of several host projects - one for each environment that the service-project resources will run within.

All of the project-factory modules assume just a single host vpc, and only set up the iam resources, especially the kubernetes-specific iam resources, for a single host project.

If, as I did, you then assume that we should not use the shared_vpc functionality exposed in these modules, but should instead use the network modules, which include a module specifically for enabling host network access in a service project, you are in for a rude awakening, because that module does not do much of the logic that is contained in the project-factory modules.  Even worse, it uses the authoritative iam_binding, so if you use that module on a project which was correctly set up in the project-factory, you will break things when the iam_binding gets overridden without all of the correct values.  Meanwhile, the project-factory modules don't allow you to specify per-subnet access controls.  

The end result is that no matter which strategy you use to set up network access, you are pretty much guaranteed to run into problems if you do anything more sophisticated than the examples - single host project, single client project, all subnets, with subnets created prior to attaching the client to the host.

**Comment by morgante** [comment]
GCP doesn't support associating a service project with multiple host projects: "each service project can only be attached to a single host project" from https://cloud.google.com/vpc/docs/shared-vpc
