### ISSUE TITLE
Output dependency in `fabric-project` broken in #284

### ISSUE THREAD

**Issue by ludoo** [terraform-google-modules/terraform-google-project-factory#308]
PR #284 that moved project services handling to a submodule broke `fabric-project` outputs, which depended on the services resource. That PR was never sent for review to a fabric project owner.

I will send a PR shortly to: a) revert the fabric project submodule to use its own resources without depending on a submodule, and b) add ourselves to CODEOWNERS for the submodule so we're looped in in all relevant PRs.

**Comment by aaron-lane** [comment]
Fixed by #309.
