### ISSUE TITLE
Update app_engine.feature_settings type and default

### ISSUE THREAD

**Issue by aaron-lane** [terraform-google-modules/terraform-google-project-factory#324]
`modules/app_engine/variables.tf` currently defines `feature_settings` as a generic `list` with a default of `[{ enabled = true }]`. The type should be updated to `list(object{ split_health_checks = bool })` since `feature_settings` can only be defined once on `google_app_engine_application` and `split_health_checks` is the only valid argument. The default should be updated to `{ split_health_checks = true}` since `false` enables legacy health checks.

https://www.terraform.io/docs/providers/google/r/app_engine_application.html#feature_settings

**Comment by bharathkkb** [comment]
@aaron-lane I can pick this up with #227

**Comment by aaron-lane** [comment]
@bharathkkb I incorrectly specified a type of `list(object{ split_health_checks = bool })` when it should have been `object{ split_health_checks = bool}` as `feature_settings` can only be specified once. Can you make the necessary change?
