### ISSUE TITLE
modify-service-account.sh fails with: ERROR: (gcloud.iam.service-accounts) Invalid choice: 'disable'.

### ISSUE THREAD

**Issue by adrian-gierakowski** [terraform-google-modules/terraform-google-project-factory#329]
```
ERROR: (gcloud.iam.service-accounts) Invalid choice: 'disable'.
This command is available in one or more alternate release tracks.  Try:
  gcloud alpha iam service-accounts disable
  gcloud beta iam service-accounts disable
```

this happened when ran with gcloud version 267.0.0
this was solved by running `gcloud components update`, which installed 272.0.0 

the script should probably check version of gcloud and use beta/alpha call when appropriate or warn user about minimum required version

**Comment by aaron-lane** [comment]
Hi @adrian-gierakowski! I apologize for the frustrating experience. We do document in the [README  Requirements > Software section](https://github.com/terraform-google-modules/terraform-google-project-factory#software) that gcloud 269 or greater is required, but that could certainly be improved with a programmatic check as you have noted.
