### ISSUE TITLE
gcloud executable requirement

### ISSUE THREAD

**Issue by marshallford** [terraform-google-modules/terraform-google-project-factory#336]
Hello,

I'd like to discuss the possibility of removing the requirement of having the `gcloud` cli available on the path to manipulate the default service account created within new projects. For those running TF from a laptop it might be reasonable to request that they install `gcloud`, but for folks using TFE or Terraform Cloud that may prove difficult.

Bottom line: Can `modify-service-account.sh` be rewritten to not rely on `gcloud`? Perhaps a native module is available and the bash script can be removed completely? It's very likely I'm missing the history/background of how this script came to be, and that's fine, just wanted to start a discussion.

Thank you!

**Comment by morgante** [comment]
Hi @marshallford, thanks for raising this.

I'm quite familiar with the pains of running gcloud in TFE or Terraform Cloud and agree we should find a solution.

We actually recently released a [gcloud](https://github.com/terraform-google-modules/terraform-google-gcloud) module which brings the gcloud sdk into a given environment for you (including TFE). We could potentially update the project-factory module to leverage that for its scripts.

Would that be an acceptable solution to you?

**Comment by marshallford** [comment]
Certainly a step in the right direction. Is it fair to say that the `gcloud` cli is required because terraform doesn't allow for resources to be defined as empty/removed/disabled? It appears the only way to communicate with terraform that a resource shouldn't exist is with a `terraform destroy` command.

General terraform question: Is this snippet theoretically possible?

```
resource "google_service_account" "service_account" {
  account_id   = "service_account_id"
  absent = true // or some inline in indicator 
}
```

**Comment by morgante** [comment]
> Certainly a step in the right direction. Is it fair to say that the gcloud cli is required because terraform doesn't allow for resources to be defined as empty/removed/disabled?

Correct. Unfortunately Terraform doesn't have any mechanism for declaring that a certain resource should be deleted.
