### ISSUE TITLE
Confusing descriptions on project_id and random_project_id

### ISSUE THREAD

**Issue by bbrouwer** [terraform-google-modules/terraform-google-project-factory#337]
The descriptions in the documentation for `project_id` and `random_project_id` are confusing at best, and are probably incorrect. For how I understand what "mutually exclusive" means, I should specify either `project_id=somevalue` or `random_project_id=true`, but not both. 

However, in looking at the code, I see no such restrictions. I can happily specify both, and end up with the project ID being `somevalue-53`, or if I specify the `name=somename`, the project ID will become either `somename-53` or just `somename`, depending on how `random_project_id` is configured. 

Am I missing something in my understanding? Could we remove those "mutually exclusive" statements and perhaps state that the `project_id` will default to the `name` provided? That seems to be how the code is written.

**Comment by morgante** [comment]
You're right, this does look incorrect/confusing. Would you be interested in providing a PR? If not one of us can probably pick it up soon.

`project_id` will indeed default to `name` if provided (and unset).
`random_project_id` will simply add a random identifier to the `project_id`.
