### ISSUE TITLE
Breaking Change Required Providers Version

### ISSUE THREAD

**Issue by BobcatProgrammer** [terraform-google-modules/terraform-google-project-factory#346]
Hi team,

as part of the PR #335 the `required_providers` for `google` was set to `"~>2.1`. This is a breaking change for me. I had it working with `~>3.0`. This was never mentioned in the changelog and I have now wasted hours finding the root cause of this as the module updated to 6.1.0 today.
The commit changing this was https://github.com/terraform-google-modules/terraform-google-project-factory/pull/335/commits/174fef7b994d0e9778d0b238dbd8c80cfd3aebd1

Can you please clarify what exact versions of the `google` provider is necessary to run this module and be more explicit about this breaking change in the Changelog.

Thanks
BobcatProgrammer

**Comment by aaron-lane** [comment]
Hi @BobcatProgrammer. I apologize for the frustrating experience. However, this is not a breaking change as the supported providers have been [documented in the README](https://github.com/terraform-google-modules/terraform-google-project-factory/commit/3a9c21389fc2f827f8cfd9a9ba6ec98e5c95be2d) for about 10 months. We have just recently moved to enforce that through configuration.

**Comment by morgante** [comment]
That being said, we can and should test whether the provider constraint could be relaxed to support 3.x as well.

**Comment by BobcatProgrammer** [comment]
@aaron-lane must have overlooked that :) . And its not 100% correct. As `~> 2.1` allows all versions `2.x`

@morgante 3.x support would be greatly appreciated. If it helps, in my (granted quite basic) setup it works without issues

**Comment by surbas** [comment]
Will add that I also got bitten by this. While it was in the readme, i didn't know about this till after everything was init using ~>3.0.0.beta.1. I bet there are a few of out there in a broken state now. 

I will also vouch for at least my stuff working on at least 3.0.0. @morgante happy to do grunt work, if guided to a procedure to use to test against the version 3 providers.

The solution if you can't rollback (like me) is to pin the version of this module to version 6.0
i.e.
```
module "project-factory" {
  source  = "terraform-google-modules/project-factory/google"
  version = "6.0" // "~> 6.0"

// ....
}
```

**Comment by morgante** [comment]
Essentially all we have to do to upgrade support to 3.0.0:
1. Review the [upgrade guide](https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html) to check if there are any features we're using.
2. Issue a PR where we change the [required providers version](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/core_project_factory/versions.tf#L20) to `>= 2.1, <4.0` and update the provider version in [examples](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/examples/simple_project/main.tf#L26) to 3.x.

**Comment by surbas** [comment]
Amazing thanks!
