### ISSUE TITLE
Shorten length of project IDs

### ISSUE THREAD

**Issue by bbrouwer** [terraform-google-modules/terraform-google-project-factory#347]
Since the max length of a project ID is 30 characters, it can get tricky to come up with meaningful names with common Google recommendations. Google often recommends a project name something like this (when using random IDs): 

`gcp-company-xxx-env-1234`

In that example, I only have 9 characters to play with. 

Could we make 2 changes to help with the situation where we're using `random_project_id`:
1. Add a `project_id_suffix` property (blank by default). In my example, I would make it be `-env`
2. Automatically shorten the project_id to `25 - len(project_id_suffix)` so I have room to add the random ID portion (30 - 5 characters for the random ID = 25). Only perform this shortening when `random_project_id=true`.

So in the example:
```
project_id = "gcp-company-someproduct"
project_id_suffix = "-env"
random_project_id = true
```
The resulting project ID would be `gcp-company-someprodu-1234-env`

By putting the suffix truly at the end will help my eye distinguish what environment it is for instead of having to look in the middle of the string for the environment.

At my company, people are not terribly interested in having random IDs in their project IDs. But when we use non random project IDs, it makes it hard to test. I would like the main project ID that people to use to be `gcp-company-someproduct-env`, but when an automated test runs, we just change `random_project_id=true`. Then we won't have to worry about project names being too long. 

I'd be willing to make a PR for this if you believe this to be a worthy idea.

**Comment by bbrouwer** [comment]
Would this happen if I submitted a PR?

**Comment by morgante** [comment]
Sure, I'd be happy to look at a PR for this (assuming that `_suffix` is optional).
