### ISSUE TITLE
"Warning: Quoted keywords are deprecated" on null_resource provisioner

### ISSUE THREAD

**Issue by Rycieos** [terraform-google-modules/terraform-google-project-factory#349]
When planning with this module, the following warning is printed 4 times:
```
Warning: Quoted keywords are deprecated

  on .terraform/modules/app_project/terraform-google-modules-terraform-google-project-factory-d9fa967/modules/core_project_factory/main.tf line 81, in resource "null_resource" "preconditions":
  81:     on_failure  = "continue"

In this context, keywords are expected literally rather than in quotes.
Terraform 0.11 and earlier required quotes, but quoted keywords are now
deprecated and will be removed in a future version of Terraform. Remove the
quotes surrounding this keyword to silence this warning.
```

The errors point to these 4 lines:

https://github.com/terraform-google-modules/terraform-google-project-factory/blob/d9fa967186e07d4800cac7e385b9cbdd165c0be9/modules/core_project_factory/main.tf#L81

https://github.com/terraform-google-modules/terraform-google-project-factory/blob/d9fa967186e07d4800cac7e385b9cbdd165c0be9/modules/core_project_factory/main.tf#L86

https://github.com/terraform-google-modules/terraform-google-project-factory/blob/d9fa967186e07d4800cac7e385b9cbdd165c0be9/modules/core_project_factory/main.tf#L198

https://github.com/terraform-google-modules/terraform-google-project-factory/blob/d9fa967186e07d4800cac7e385b9cbdd165c0be9/modules/core_project_factory/main.tf#L226

TF and provider versions:
```
$ tf --version
Terraform v0.12.18
+ provider.google v2.20.1
+ provider.google-beta v2.20.1
+ provider.null v2.1.2
+ provider.random v2.2.1
```

This warning happens with older versions too, back to [version `0.12.14` ](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#01214-november-13-2019)

**Comment by morgante** [comment]
Looks like a simple fix, happy to accept a PR!

**Comment by Rycieos** [comment]
It looks like thanks to #343 and now #357, there are no more references to `"continue"`, so I think there is nothing left to do.
