### ISSUE TITLE
Disable automatic downloading of Cloud SDK

### ISSUE THREAD

**Issue by dmcgowandmc** [terraform-google-modules/terraform-google-project-factory#352]
I have been using a terraform docker container with Cloud SDK and supporting libraries added to the image to perform my deployments. This has worked well in the past allowing me to ensure all required binaries and libraries are in place before deployment. This allowed me to peg the versions exactly as desired and deployments were generally pretty quick.

However it seems since 6.2.0, project factory tries to download all this for you during an apply. This has removed version control and has slowed down deployments significantly as Cloud SDK is getting downloaded every-time the project factory is been used where it really only needed to be installed once.

I can see the reason this was done, you want to ensure the right version of Cloud SDK is been used, but is it possible to disable this if desired and just rely on the user to install the Cloud SDK beforehand?

**Comment by morgante** [comment]
Yes, I think this is a reasonable suggestion. I think it could be implemented by:
1. Adding a `skip_download` variable to the [gcloud](https://github.com/terraform-google-modules/terraform-google-gcloud) module
2. Exposing that variable in this module as well

**Comment by rjerrems** [comment]
Not sure if this will be solved by the same `skip_download` flag, but since version 6.2.* onwards every time you run an apply, terraform needs to recreate these resources even when gcloud is already cached locally

```  # module.project-factory.module.project-factory.module.gcloud_disable.null_resource.copy[0] must be replaced
-/+ resource "null_resource" "copy" {
      ~ id       = "7794951087348461094" -> (known after apply)
      ~ triggers = {
          - "always" = "a9adfc4b-0d97-b9e4-9ea8-092df9394a23"
        } -> (known after apply) # forces replacement
    }

  # module.project-factory.module.project-factory.module.gcloud_disable.null_resource.decompress[0] must be replaced
-/+ resource "null_resource" "decompress" {
      ~ id       = "627270122008474692" -> (known after apply)
      ~ triggers = {
          - "always" = "aa2feb58-efc7-a4a8-7c60-03449372f05a"
        } -> (known after apply) # forces replacement
    }

  # module.project-factory.module.project-factory.module.gcloud_disable.null_resource.upgrade[0] must be replaced
-/+ resource "null_resource" "upgrade" {
      ~ id       = "5590880360948684469" -> (known after apply)
      ~ triggers = {
          - "always" = "b49f2dee-d0f9-6093-8272-0347ebb863be"
        } -> (known after apply) # forces replacement
    }
```
Should we address as a part of this issue or shall I raise a new one?

**Comment by morgante** [comment]
@rjerrems I think that's a different issue, let's track it separately.

**Comment by rjerrems** [comment]
No problem @morgante - I have create #363

**Comment by MajorBreakfast** [comment]
Implemented in https://github.com/terraform-google-modules/terraform-google-project-factory/pull/393

**Comment by dmcgowandmc** [comment]
Thanks @morgante , I'll arrange to upgrade to version 7.1.0 to try it out!
