### ISSUE TITLE
Make prefix optional or document why it is a good practice

### ISSUE THREAD

**Issue by NVolcz** [terraform-google-modules/terraform-google-project-factory#355]
It is not clear whenever prefixing project names is a common good practice or a bug. I have found some references that indicates that this previously was a relatively common but I cannot find any recent post about this being still being recommended. Let's document it in the FAQ (or somewhere else) if it still is a common practice.

**Comment by morgante** [comment]
Can you clarify where you see this required?

It's encouraged to help with globally unique project IDs but not required.

**Comment by NVolcz** [comment]
The input variable prefix in for the fabric project: https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/fabric-project

**Comment by morgante** [comment]
I see. Please just use the main project factory if you don't want to use prefixes.

The fabric project is a specialized prototyping use case not recommended for everyone.

**Comment by NVolcz** [comment]
Thanks for the clarification!
