### ISSUE TITLE
Failed to download the project factory module

### ISSUE THREAD

**Issue by Deepak275** [terraform-google-modules/terraform-google-project-factory#359]
Hi Team,

Deepak here. Need your help to check this error we start getting from today.. Is there anything changed ? We were using 3.0.0, but as it start failing i tried 3.1.0 and the latest one too, but got the same error. Please help 🙏 

> Error: Failed to download module
> 
> Could not download module "service_project"
> (.terraform/modules/gjk-allocation-prd-01/service_project.tf:9) source code
> from
> "https://api.github.com/repos/terraform-google-modules/terraform-google-project-factory/tarball/v6.2.1//*?archive=tar.gz":
> Error opening a gzip reader for
> /var/folders/5m/gzh4hv1s7wx61mxc55fhlmjh0000gn/T/getter795056107/archive: EOF.

**Comment by Deepak275** [comment]
getting this 

`$ wget https://api.github.com/repos/terraform-google-modules/terraform-google-project-factory/tarball/v3.1.0//*?archive=tar.gz
Warning: wildcards not supported in HTTP.
--2020-01-10 15:24:39--  https://api.github.com/repos/terraform-google-modules/terraform-google-project-factory/tarball/v3.1.0//*?archive=tar.gz
Resolving api.github.com (api.github.com)... 13.233.76.15
Connecting to api.github.com (api.github.com)|13.233.76.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/terraform-google-modules/terraform-google-project-factory/legacy.tar.gz/v3.1.0//* [following]
Warning: wildcards not supported in HTTP.
--2020-01-10 15:24:39--  https://codeload.github.com/terraform-google-modules/terraform-google-project-factory/legacy.tar.gz/v3.1.0//*
Resolving codeload.github.com (codeload.github.com)... 13.233.43.20
Connecting to codeload.github.com (codeload.github.com)|13.233.43.20|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-01-10 15:24:40 ERROR 404: Not Found.`

**Comment by ibacalu** [comment]
try replacing with actual git https url. That should fix it.

**Comment by bharathkkb** [comment]
I ran into this and I think this maybe a terraform bug. I was able to solve it by upgrading to v0.12.19. 
Here is the issue on terraform https://github.com/hashicorp/terraform/issues/23721

**Comment by Deepak275** [comment]
@bharathkkb This was because terraform registry was down for more than 16 hours, this is the message i saw in their website. Yes They mentioned that upgrading to **v0.12.19.** will solve this issue.

> Identified - We've identified the cause of the failures and are implementing a fix to restore services.
> Users on Terraform 0.12.19 will not experience any issues. You can upgrade to 0.12.19 to resolve the issue. We are currently investigating potential fixes for older versions.
> Jan 9, 21:15 UTC
> Investigating - Terraform Registry is experiencing an issue that affects the availability of the service. We are currently working to identify the source of the outage and restore services.
> Jan 9, 20:42 UTC

**Comment by Deepak275** [comment]
It's up now, so closing the issue.
