### ISSUE TITLE
precondition fails on ubuntu

### ISSUE THREAD

**Issue by shraddhajain01** [terraform-google-modules/terraform-google-project-factory#360]
I tried to create a simple project using "simple_project" example, it is failing at 'terraform apply' with below error:

Error: Error running command '/XXX/XXX/terraform-google-project-factory/examples/simple_project/.terraform/modules/project-factory/modules/core_project_factory/scripts/preconditions/requirements.txt': exec: "pip3": executable file not found in $PATH. Output:

**Comment by morgante** [comment]
You need to have Python or pip3 installed to let the precondition script work.

You can also upgrade to the 7.x version which will allow the precondition script to fail without preventing `apply` entirely.

**Comment by shraddhajain01** [comment]
Got it. It worked by installing pip, although python was already installed on the machine. Thank you.
