### ISSUE TITLE
how to create service account for project creation using this module

### ISSUE THREAD

**Issue by SprintCT** [terraform-google-modules/terraform-google-project-factory#370]
Hi,

I unable to understand how to create Service account at org level in GCP to create the folder/project creation to working on this module. As per module i have to place file the credential path. Since i unable to create a service i unable to provide it.
Kindly assist me on this.

Example:
I got Admin access for org level. And i have created a member (not service account) and provide access to folder creator role and project create role. Now i don't know how to use this module.

**Comment by morgante** [comment]
As I understand it, your personal user account has admin access. In that case, you can run `gcloud auth application-default login` to authenticate Terraform and this module, as per the [Terraform docs](https://www.terraform.io/docs/providers/google/guides/provider_reference.html#credentials-1).

**Comment by SprintCT** [comment]
I want to know how i need to parse this value in pipeline as code automation, I didnt use my desktop use this terraform module, It will run in pipeline as code, so is there any way to create service account

**Comment by michaeldeman** [comment]
Best practices dictate that key management is done separately from terraform & provisioning itself.
If you have your bootstrap/seed project setup already, then inside the `helpers` folder you can run `setup-sa.sh` to create the service account.  After that, you will want to access the cloud console from your web browser to generate a key pair and download the private key for installation into your CICD pipeline tooling.
