### ISSUE TITLE
Preconditions doesn't use the right project id

### ISSUE THREAD

**Issue by umairidris** [terraform-google-modules/terraform-google-project-factory#372]
module "project" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 6.0"

  name                = "foo"
  project_id          = "foo"
  org_id              = "123"
  billing_account     = "000"
}

I expect the preconditions script to check project foo. Instead it is using the project set in gcloud (checked with `gcloud config get-value project`).

I get the following error:
```
Error: Error running command 'python3 project/.terraform/modules/project/modules/core_project_factory/scripts/preconditions/preconditions.py --billing_account="000" --credentials_path="" --folder_id="" --impersonate_service_account="" --org_id="123" --shared_vpc="" ': exit status 1. Output: /usr/local/google/home/umairidris/.local/lib/python3.7/site-packages/google/auth/_default.py:69: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
WARNING:googleapiclient.http:Invalid JSON content from response: b'{\n  "error": {\n    "code": 403,\n    "message": "The caller does not have permission",\n    "status": "PERMISSION_DENIED"\n  }\n}\n'
Traceback (most recent call last):
  File "project/.terraform/modules/project/modules/core_project_factory/scripts/preconditions/preconditions.py", line 484, in <module>
    retcode = main(sys.argv)
  File "project/.terraform/modules/project/modules/core_project_factory/scripts/preconditions/preconditions.py", line 466, in main
    results.append(validator.validate(credentials))
  File "project/.terraform/modules/project/modules/core_project_factory/scripts/preconditions/preconditions.py", line 254, in validate
    response = request.execute()
  File "/usr/local/google/home/umairidris/.local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/google/home/umairidris/.local/lib/python3.7/site-packages/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
```
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://serviceusage.googleapis.com/v1/projects/GCLOUD_PROJECT/services/admin.googleapis.com?alt=json returned "The caller does not have permission">

**Comment by morgante** [comment]
This isn't quite what's going on and this is exactly why we *have* the preconditions script. If you had attempted to proceed with project creation, it would fail.

First of all, the point of project factory is to *create* project `foo`. So of course we can't check APIs on project `foo` since it doesn't exist yet.

But then why are we checking APIs at all, you might ask?

Because the APIs need to be active somewhere (or else you will get unrecoverable API issues).

Specifically, it's checking the APIs which are active wherever your *credentials* are coming from. Because that's where the APIs are going to check if they're active.

**Comment by umairidris** [comment]
Following up after offline discussion:
- This check is useful when the module is being run by a service account as the service account's project might not have the API enabled
- When running as local user the default gcloud project is used

I was running as option 2 so my project creation would have succeeded. Is there a way for the precondition script to know I am not a service account? I guess a hacky way would be to get the user email and look for 'gserviceaccount' or something as the domain.

Anyways, I got around this by just changing the project set from an old undeleted one which fixed the problem. Feel free to close if needed. Thanks!

**Comment by morgante** [comment]
I think the ideal thing would be for us to check the actual project where your credentials are coming from, but I'm not sure if that's possible.
