### ISSUE TITLE
gcloud_bin_abs_path changes on re-apply

### ISSUE THREAD

**Issue by dwilliams782** [terraform-google-modules/terraform-google-project-factory#391]
Running a plan/apply on different machines produces the following diff:

```
# module.project_mobile.module.project-factory.module.gcloud_disable.null_resource.run_command[0] must be replaced
-/+ resource "null_resource" "run_command" {
      ~ id       = "9166635190702597732" -> (known after apply)
      ~ triggers = { # forces replacement
            "destroy_cmd_entrypoint"  = "gcloud"
          ~ "gcloud_bin_abs_path"     = "<local-path>.project-factory.gcloud_disable/terraform-google-modules-terraform-google-gcloud-09a6f10/cache/9272b146/google-cloud-sdk/bin" -> "<local-path>.project-factory.gcloud_disable/terraform-google-modules-terraform-google-gcloud-09a6f10/cache/9272b146/google-cloud-sdk/bin"
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

Truncated the local paths, but it appears to be downloading the gcloud bin and storing the path in state, which isn't what we want to do. I noticed the skip_download variable but that isn't exposed to the project-factory module yet?

Apologies if it's a duplicate, I had a search and couldn't see anything.

**Comment by morgante** [comment]
Unfortunately I don't think there's actually any way to get around this, as Terraform *requires* everything in the null_resource command to be a trigger and we need to know the gcloud path.

Fortunately, you can safely apply the local-exec multiple times (it's idempotent).

**Comment by thesuperzapper** [comment]
@morgante isn't `self.triggers.gcloud_bin_abs_path` also stored as a `local.gcloud_bin_abs_path`?

Why cant we just remove `gcloud_bin_abs_path` from the triggers and use the the local variable in our local-exec?

**Comment by morgante** [comment]
That's actually how it used to be: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/420/files

But then https://github.com/hashicorp/terraform/issues/23679 (in Terraform core) started warning/deprecating this behavior, so we can *only* access triggers.

**Comment by dwilliams782** [comment]
> Fortunately, you can safely apply the local-exec multiple times (it's idempotent).

Whilst this is true, it muddies up our plans in our CI pipeline, so we have had to move away from using this module.

**Comment by thesuperzapper** [comment]
Lets discuss this in #396

**Comment by Luke-Vear** [comment]
> #396

That issue is closed, but it didnt seem to have a resolution for this problem

**Comment by thesuperzapper** [comment]
@morgante I am still having this issue with `v8.0.1`

**Comment by morgante** [comment]
@thesuperzapper Can you try setting `skip_gcloud_download` to true? That should workaround the issue.

**Comment by thesuperzapper** [comment]
@morgante, I am setting that to true already.

**Comment by morgante** [comment]
Odd, I think we'll have to fix this in the gcloud module.

**Comment by bharathkkb** [comment]
Should not be relevant as gcloud module has been replaced by #491
