### ISSUE TITLE
Module can not be used with Terraform 0.12.2 and recent provider

### ISSUE THREAD

**Issue by Jberlinsky** [terraform-google-modules/terraform-google-project-factory#392]
There exists no version of this module that will work out of the box with Terraform 0.12.2, and a recent (>= 3.0.0) version of the `google` provider.

v3.3.1 is the latest version of this module that does not use `for_each`, for which support was only added in Terraform 0.12.6. However, this version [uses](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/v3.3.1/modules/core_project_factory/main.tf#L165) the `google_project_services` resource, which was [removed](https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#resource-google_project_services) in version 3 of the `google` provider. Even when `var.apis_authority` is set to `0`, Terraform returns an error because `google_project_services` is not known to the provider.

The solution I've landed on short-term is to specify the following version constraint in my root module:

```
terraform {
  required_providers {
    google = "< 3.0"
  }
}
```

I suggest that this module be changed such that:

- In the immediate term, this version constraint should be applied to module versions prior to `v3.3.1`
- An update should be released to versions prior to `4.0.0` that render them functional on newer versions of the `google` provider. It appears at a quick glance that this is the only significant incompatibility (at least for `v3.3.1`), so perhaps releasing a `v3.3.2` with `google_project_services` removed and replaced with a `count`-looped `google_project_service` might be an adequate short-term solution.

**Comment by morgante** [comment]
We could add a version constraint, but frankly supporting old versions of Terraform is not a priority. The best resolution is to upgrade your version.
