### ISSUE TITLE
svpc attachment failing on missing compute.organizations.enableXpnResource permission

### ISSUE THREAD

**Issue by marc-leblanc** [terraform-google-modules/terraform-google-project-factory#395]
Unable to create SVPC attachment. 

```
Error: googleapi: Error 403: Required 'compute.organizations.enableXpnResource' permission for 'projects/ssvpc'
More details:
Reason: forbidden, Message: Required 'compute.organizations.enableXpnResource' permission for 'projects/svpc'
Reason: forbidden, Message: Required 'compute.organizations.enableXpnResource' permission for 'projects/test-demo-8186'


  on ../../../modules/terraform-google-modules/terraform-google-project-factory/modules/core_project_factory/main.tf line 136, in resource "google_compute_shared_vpc_service_project" "shared_vpc_attachment":
 136: resource "google_compute_shared_vpc_service_project" "shared_vpc_attachment" {

```

Things I have verified:
* Able to use the same service account to create the attachment via gcloud CLI. Works fine
* Granted the `compute.organizations.enableXpnResource` on the organization. Fails in TF
* Granted the `compute.organizations.enableXpnResource` on the folder/project. Also fails in TF
* Manually granted all of the permissions listed for requirements. Fails.
* Used the `/helpers/setup_sa.sh` script to create the seed account on the organization (no folder). Also fails.

**Comment by morgante** [comment]
Please double check which account you're using in Terraform. This is very unlikely to be a bug in the module, since all we're doing is using the resource + API call.

**Comment by marc-leblanc** [comment]
Double checked. 
I have cooked up a pretty simple scenario. 

I have credentials_path set to the path to the json service account key file. The SVPC in this case pre-exists. The service account I created has roles/permissions set from the setup_sa.sh script. 

Project factory  can create the new service project, but when it goes to attach it, it fails on the xpn permission every time. 

I did a test, and I let project factory  create the project, and then I set up the following smaller test:
```
provider "google" {
  credentials = file("project-factory.json") #same key file used in the failing terraform
}

resource "google_compute_shared_vpc_service_project" "shared_vpc_attachment" {
  host_project    = "svpc_host" #project created previously
  service_project = "service_project" #project created previously

}
```
This works fine, same key  file.

**Comment by morgante** [comment]
To confirm, is your provider block configured the same way when invoking Project Factory?

**Comment by morgante** [comment]
@marc-leblanc Is this still an issue?

**Comment by marc-leblanc** [comment]
I have to come back to it when I have time. I think I know what was causing it. Close for now.
