### ISSUE TITLE
Using budgets.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [terraform-google-modules/terraform-google-project-factory#405]
What should be the iam permissions for project creating service account in order to use budgets?
I am getting an error with the org level billingUser IAM role:
```

Error: Error creating Budget: googleapi: Error 403: The caller does not have permission

  on .terraform/modules/mikhail_poc_project.host-project/terraform-google-project-factory-8.0.0/modules/budget/main.tf line 31, in resource "google_billing_budget" "budget":
  31: resource "google_billing_budget" "budget" {

``` 
can the role be set on the folder rather than the org?

**Comment by morgante** [comment]
You need the billing admin role, as explained here: https://cloud.google.com/billing/docs/how-to/billing-access

Billing IAM cannot be managed on folders, only orgs or billing accounts.
