### ISSUE TITLE
activate_apis parameter is using count instead of for_each

### ISSUE THREAD

**Issue by red8888** [terraform-google-modules/terraform-google-project-factory#406]
I specify activate_apis like this:

```
  activate_apis = [
    "compute.googleapis.com",
    "iam.googleapis.com",
    "oslogin.googleapis.com",
    "runtimeconfig.googleapis.com",
    "iamcredentials.googleapis.com",
]
```

Now lets say I want to reorder that to group similar APIs together:
```
  activate_apis = [
    "compute.googleapis.com",
    "oslogin.googleapis.com",
    "iam.googleapis.com",
    "iamcredentials.googleapis.com",
    "runtimeconfig.googleapis.com",
]
```

Because this module is using count its a destructive operation. terraform 0.12 fixed this problem. count should only be used where you really need to preserve order and destroy/recreate if that order is changed. Here order is totally arbitrary

Why is this module using count instead of for_each here?

**Comment by morgante** [comment]
Please make sure you're using the latest module version (8.0.0). This has been fixed since the 4.0.0 release: https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/CHANGELOG.md#400---2019-10-21
