### ISSUE TITLE
Remove preconditions script

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-project-factory#407]
In order to remove the [preconditions script](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/core_project_factory/scripts/preconditions/preconditions.py) from the module (#373), we need to confirm it's impossible to start module creation and be left in a catastrophic state.

Therefore we need to make sure each step has an associated in-provider check and we document/explain in the troubleshooting guide.

Checks:
- [ ] Seed project - check that APIs are active
  * [x] [cloudresourcemanager.googleapis.com](#missing-api-cloudresourcemanagergoogleapiscom)
  * [x] [cloudbilling.googleapis.com](#missing-api-cloudbillinggoogleapiscom) - fixed via https://github.com/terraform-providers/terraform-provider-google/pull/5671
  * [x] [iam.googleapis.com](#missing-api-iamgoogleapiscom)
  * [x] [appengine.googleapis.com](#missing-appenginegoogleapiscom) (when managing an App Engine instance on the Target Project)
  * [x] [admin.googleapis.com](#missing-admingoogleapiscom) (when managing G Suite
  groups and group membership)
  * [x] `serviceusage.googleapis.com` - needed to remove default network - https://github.com/terraform-providers/terraform-provider-google/issues/6222
- [x] Confirm permissions on billing account
- [x] Confirm permissions on Shared VPC
- [x] Confirm permissions on organization
- [x] Confirm permissions on folder

**Comment by thiagonache** [comment]
@morgante I know it's silly, but what if we force serviceusage to be enabled until we get it handled by the provider?
```
variable "activate_apis" {
  description = "The list of apis to activate within the project"
  type        = list(string)
  default     = ["compute.googleapis.com"]

  validation {
    condition     = can(lookup(var.activate_apis, "serviceusage.googleapis.com"))
    error_message = "Service Usage API is required due to network auto creation."
  }
}
```

Just a thought....

**Comment by morgante** [comment]
@thiagonache It actually doesn't need to be enabled on the project being created, it needs to be on the credentials project.

**Comment by thiagonache** [comment]
Doh!
Do you think they would accept the new resource to remove the default network? If yes, I can see if I can do it. I think I can.

**Comment by thiagonache** [comment]
Hi @morgante! We got a small change merged that handles the serviceusage API. I know it's not your preferred way due to other possible errors, but I think if we tackle the most recurrent ones is enough to get rid of the preconditions script.

What do you think?

**Comment by morgante** [comment]
Yeah I think this is enough to drop it. If you could file a PR moving to to `helpers/` and removing it from module code that would be great. We should also document how to run it standalone (ie. before running Terraform).

**Comment by thiagonache** [comment]
sure. will do.

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-project-factory/pull/478
