### ISSUE TITLE
Remove gcloud dependency

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-project-factory#408]
We would like to remove all null_resources from this module and not require gcloud in the execution environment.

This will require:
- [ ] Removing the need for the precheck script: #407
- [ ] Adding native Terraform support to handle deleting/disabling the default service account

**Comment by bharathkkb** [comment]
>Adding native Terraform support to handle deleting/disabling the default service account

@morgante this would be in the provider right?

**Comment by morgante** [comment]
> @morgante this would be in the provider right?

Correct

**Comment by umairidris** [comment]
Does the org policy `constraints/iam.automaticIamGrantsForDefaultServiceAccounts` remove the need for step 2?

**Comment by morgante** [comment]
Unfortunately that doesn't support cases where you don't manage the org policies for the organization or folder. (Even `google.com` is an example.)

**Comment by leone145** [comment]
I would like to see this. If the module.gcloud_deprivilege.null_resource.run_command[0] becomes tainted and editor was previously removed, it will not apply without manual intervention.

**Comment by djbingham** [comment]
I would also love to see this. I've abandoned plans to use Terraform Cloud because I couldn't get this module to work properly (Terraform Cloud doesn't have `gcloud` in its execution environment).

Would a reasonable alternative (or temporary) solution be to depend on the [`gcloud` Terraform module](https://registry.terraform.io/modules/terraform-google-modules/gcloud/google/1.0.1), rather than requiring `gcloud` to be pre-installed in the execution environment? Other modules do that and seem to work ok.

**Comment by morgante** [comment]
@djbingham Yes that would be a reasonable workaround to get this working on Terraform Cloud. I haven't had cycles to work on it, but I'd be happy to review a PR.

**Comment by thiagonache** [comment]
@morgante can you mark task number one as done and update the second task with currently [issue](https://github.com/hashicorp/terraform-provider-google/issues/4135) on the provider repo, please? I'll try to get this done.

**Comment by thiagonache** [comment]
@morgante we have the new resource on the master of terraform provider.
I've been thinking about how to remove gcloud. Maybe we can add the new resource and remove the gcloud local exec but keep the variables to avoid a breaking change, but we'll need to remove these variables at some point. Or let's just assume it is a breaking change?

**Comment by morgante** [comment]
@thiagonache Which variables are you referring to?

**Comment by thiagonache** [comment]
Download gcloud ie

**Comment by thiagonache** [comment]
```variable "use_tf_google_credentials_env_var" {
  description = "Use GOOGLE_CREDENTIALS environment variable to run gcloud auth activate-service-account with."
  type        = bool
  default     = false
}

variable "skip_gcloud_download" {
  description = "Whether to skip downloading gcloud (assumes gcloud is already available outside the module)"
  type        = bool
  default     = false
}```
My understanding is that we don't need these two variables anymore.

**Comment by thiagonache** [comment]
I've drafted a PR it is working on my machine, but we'll have to wait until the next release of terraform google provider.
https://github.com/terraform-google-modules/terraform-google-project-factory/pull/491

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-project-factory/pull/491
