### ISSUE TITLE
Terraform Destroy fails on disabling project APIs

### ISSUE THREAD

**Issue by max-nzta** [terraform-google-modules/terraform-google-project-factory#410]
Hi guys,

I have a pretty simple script to create a project. 
```
provider "google" {
  credentials = file(var.credentials_file_path)
  region      = var.region
}

provider "google-beta" {
  credentials = file(var.credentials_file_path)
  region      = var.region
}

provider "null" {}

locals {
  default-services = [
    "compute.googleapis.com",
    "storage-api.googleapis.com"
  ]
}

module "project-factory" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~>7.0"

  org_id                  = var.organization_id
  billing_account         = var.billing_account
  folder_id               = var.folder_id
  name                    = var.project_name
  project_id              = "${var.product_fla}-${terraform.workspace}"
  auto_create_network     = "false"
  credentials_path        = var.credentials_file_path
  default_service_account = "keep"
  random_project_id       = var.random-project-id
  labels                  = {
     some labels are here
  }
  activate_apis           = concat(var.activate_apis, local.default-services)
}
```

It creates a project just fine. I am using the following command. All variables are present.

`terraform destroy -var-file dev.tfvars -var-file override.tfvars -auto-approve`

 Then I try to drop the project by running this command
`terraform apply -var-file dev.tfvars -var-file override.tfvars -auto-approve`

When dropping the project Terraform is failing with the following
```
Error: Error reading Project Service pe-2e2-test-default-6a86/compute.googleapis.com: Error disabling service "compute.googleapis.com" for project "pe-2e2-test-default-6a86": googleapi: Error 400: Precondition check failed., failedPrecondition
Error: Error reading Project Service pe-2e2-test-default-6a86/pubsub.googleapis.com: Error disabling service "pubsub.googleapis.com" for project "pe-2e2-test-default-6a86": googleapi: Error 400: Precondition check failed., failedPrecondition
Error: Error reading Project Service pe-2e2-test-default-6a86/storage-api.googleapis.com: Error disabling service "storage-api.googleapis.com" for project "pe-2e2-test-default-6a86": googleapi: Error 400: Precondition check failed., failedPrecondition
```

This behaviour is not consistent. Sometimes it fails with the above errors, sometimes with trying to disable different APIs, sometimes it passes OK. Note that all other resources are destroying successfully. It's only the APIs left that can't be disabled.

First I thought that I drop the project too soon after creating it. So I put some wait time in between apply and destroy. It didn't help. I though maybe it was still not enough time to enable the API property. So I left the created project over a weekend. On Monday morning I tried to drop the project created the Friday before that and I got the same type of errors. 

TRACE logs don't show anything - just the same message: Error 400: Precondition check failed.

**Comment by morgante** [comment]
Unfortunately it's likely that you still have some resources using these APIs.

If you're trying to delete the whole project you can set `disable_services_on_destroy = false` to skip disabling services and simply destroy the whole project.

**Comment by max-nzta** [comment]
@morgante thanks for your response. Setting the `disable_services_on_destroy` flag to false didn't work. But setting additionally the `disable_dependent_services` to false did the trick. It's working now.
