### ISSUE TITLE
Downloading terraform-google-modules/gcloud/google not working

### ISSUE THREAD

**Issue by ElyKhama** [terraform-google-modules/terraform-google-project-factory#412]
I'm trying to create a project with project-factory module :
```
module "project_common" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 8.0"
  name            = local.project_common_project_id
  project_id      = local.project_common_project_id
  folder_id       = local.project_common_folder_id
  org_id          = var.org_id
  billing_account = var.billing_account
  activate_apis   = var.activate_apis
}
```

But when I do terraform init I have this :
`Downloading terraform-google-modules/gcloud/google 1.0.0 for project_common.project-factory.gcloud_delete...`

It's stuck for hour. Other modules (e.g cloud-nat) are downloading well.

To reproduce just remove your .terraform folder and run `terraform init` again on a workspace using project-factory module.

**Comment by morgante** [comment]
What version of Terraform are you using? `terraform -v`

**Comment by ElyKhama** [comment]
I'm using Terraform v0.12.24.
Sorry I should have misconfigured something, it works on old projects I have, same environment.
