### ISSUE TITLE
org_id required even if only creating project in folder

### ISSUE THREAD

**Issue by umairidris** [terraform-google-modules/terraform-google-project-factory#413]
The org_id should not be required if the user is only creating a project in the folder.

**Comment by morgante** [comment]
What's the use case for not requiring it?

In general we're trying to keep a simpler interface with less variations. For that, it's simpler to assume we always know the org ID.

**Comment by umairidris** [comment]
We were working with a customer who was setting up a new app in a folder which was already created and their org setup.

They wanted to do everything inside this folder and thus were going through and removing/replacing any org references/resources.

When it came to project they tried to deploy but then saw the org id is required. They were able to get past this by just setting a dummy org_id like "123" to make sure it doesn't try to make changes on their real org.

So in general I didn't see a benefit from forcing users to get the real org id if they don't need it.

**Comment by morgante** [comment]
The issue is that some features (around group management/access) do require looking up info about the org ID. Creating inside a folder is fully supported, of course.

There isn't any harm in requiring org ID, while conditionally excluding it would require meaningful additional logic.

**Comment by umairidris** [comment]
Ah, we weren't setting up group management so I wasn't aware. If it makes things more complex then no need to change it, thanks.

**Comment by umairidris** [comment]
p.s. just setting org_id to "" is usually sufficient in bypassing this.
