### ISSUE TITLE
Unable to import Google API dependencies, skipping GCP precondition checks!

### ISSUE THREAD

**Issue by sbadakhc** [terraform-google-modules/terraform-google-project-factory#417]
This seems to be an issue with pip attempting to install as root modules as root. I using Fedora Linux. Its probably a good idea to use the --user flag when executing pip.

```
module.org_monitoring_prod.module.project-factory.null_resource.preconditions (local-exec): Unable to import Google API dependencies, skipping GCP precondition checks!
```

**Comment by morgante** [comment]
To get around this, I'd recommend simply installing the pip requirements out-of-band.

**Comment by sbadakhc** [comment]
Will do to work around this. Perhaps the module can be updated to execute with the --user option in the future?

Thanks,
Sal.

**Comment by morgante** [comment]
We're actually hoping to deprecate the precondition script entirely - #407.
