### ISSUE TITLE
Enable shared_vpc_host to be set using project factory 

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-project-factory#422]
Currently inorder to create a project as a SVPC host project, we have to either
- Create project using PF and then use `google_compute_shared_vpc_host_project` to mark it as SVPC host
- [Use Network module ](https://github.com/terraform-google-modules/terraform-google-network)

We should consider wrapping `google_compute_shared_vpc_host_project` within PF similar to [how we attach as a service project.](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/9da81586f218c13c69f13a4034f606203ac8187c/modules/core_project_factory/main.tf#L136)

**Comment by morgante** [comment]
I think this is a reasonable addition. We could expose an `enable_shared_vpc_host` variable.

**Comment by thiagonache** [comment]
we can close this issue, can't we?
