### ISSUE TITLE
Fabric project doesn't support having a human readable name

### ISSUE THREAD

**Issue by preston-hf** [terraform-google-modules/terraform-google-project-factory#425]
I am using the fabric project with prefixes, and this gives the end users a less than ideal experience when looking at projects. I would like to have the option to supply a human readable name in addition to the project_id, instead of [forcing](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/fabric-project/main.tf#L33) them to be identical. I am happy to propose a PR for this if the maintainers approve of this request.

**Comment by morgante** [comment]
At this point, I don't think we want to add new features to fabric project. It was mostly experimental and I expect we might remove it in the future.

Is there a reason you can't use the main project factory? It should support the human readable name you need.

**Comment by preston-hf** [comment]
That's good to know. I have been using it heavily as it is very minimal which for my usage was desirable. I'm not sure exactly why I went with it ultimately, but that was my overall goal. What was the experiement?

Thanks

**Comment by morgante** [comment]
Trying to upstream some more minimal examples, but truthfully we've found that the core project factory should work fine. You can easily turn off features that you don't use there.
