### ISSUE TITLE
Relative credentials_path won't work

### ISSUE THREAD

**Issue by bvarga** [terraform-google-modules/terraform-google-project-factory#429]
Hi,

When providing a relative path, got an error:

```
module "project-factory" {
  source               = "terraform-google-modules/project-factory/google"
  version              = "~> 8.0"
  name                 = "something"
  random_project_id    = "true"
  org_id               = "otgid"
  billing_account      = "billingid"
  credentials_path     = "~/.config/gcloud/terraform-admin.json"
  skip_gcloud_download = true
}
```

`': exit status 1. Output: ERROR: (gcloud.iam.service-accounts.list) Failed to load credential file: [~/.config/gcloud/terraform-admin.json].  The parameter passed to the from_stream() method should point to a file.
`

if use absolute path, everything works as expected.

Also I can make it work if I wrap it to terraform function `pathexpand()`, but maybe a relative path should work too.

Regards
Balazs

**Comment by morgante** [comment]
We could add `pathexpand` or `abspath` inside the module to fix this.

**Comment by bharathkkb** [comment]
closing this as `credentials_path` is no longer needed due to #407. Tracking removal of var in #523
