### ISSUE TITLE
Billing account: precondition check failed on project creation

### ISSUE THREAD

**Issue by dmedora** [terraform-google-modules/terraform-google-project-factory#430]
Hello, 

When attempting to create projects using the `project-factory` module, I receive the below error related to setting a billing account. I am creating ~8 projects in the same way. Usually, around 2 or 3 of them will get this error, while the rest are successful. Perhaps there is a race condition with the billing account being set before the project is ready?

```
Error: Error setting billing account "<billing account id>" for project "projects/project1-5933": googleapi: Error 400: Precondition check failed., failedPrecondition

  on .terraform/modules/project1/terraform-google-project-factory-8.0.1/modules/core_project_factory/main.tf line 96, in resource "google_project" "main":
  96: resource "google_project" "main" {
```

Sample module block:
```
module "project1" {
  source            = "terraform-google-modules/project-factory/google"
  name              = "project1"
  random_project_id = true
  org_id            = var.org_id
  folder_id         = local.root_folder_id
  billing_account   = var.billing_account_id
}
```

Thanks!

**Comment by bharathkkb** [comment]
Hi @dmedora could you check if it is due to this https://github.com/terraform-google-modules/terraform-google-project-factory/issues/28#issuecomment-422178737

**Comment by dmedora** [comment]
It is in fact the same issue - thank you for the quick help!
