### ISSUE TITLE
shared_vpc_access module is broken

### ISSUE THREAD

**Issue by MajorBreakfast** [terraform-google-modules/terraform-google-project-factory#442]
It seems to be referencing non-existant resources:

https://github.com/terraform-google-modules/terraform-google-project-factory/blob/dd2dd997650ebea9df220bc750a21a6e813cc962/modules/shared_vpc_access/outputs.tf#L26-L28

- There's no `google_compute_subnetwork_iam_member.gke_dataproc_shared_vpc_subnets` resource defined in this module
- There's no `google_project_iam_member.gke_dataproc_shared_vpc_network_user` resource defined in this module

**Comment by MajorBreakfast** [comment]
https://github.com/terraform-google-modules/terraform-google-project-factory/pull/441 fixes this issue

**Comment by bharathkkb** [comment]
fixed by #441
