### ISSUE TITLE
shared_vpc module has an unintuitive name

### ISSUE THREAD

**Issue by MajorBreakfast** [terraform-google-modules/terraform-google-project-factory#444]
The name does not suggest that it actually creates a project, but it does. Looking at the code it's mostly the same as the root module. It only contains an instance of the shared_vpc_access module extra.

**Comment by morgante** [comment]
These are all part of the project factory so I don't think we will rename.

I'd be happy to accept a PR adding a README though.

**Comment by bharathkkb** [comment]
Renamed via https://github.com/terraform-google-modules/terraform-google-project-factory/pull/517 and added readme via https://github.com/terraform-google-modules/terraform-google-project-factory/pull/513
