### ISSUE TITLE
shared_vpc features is broken (or removed) from root module

### ISSUE THREAD

**Issue by askoriy** [terraform-google-modules/terraform-google-project-factory#445]
After upgrade to version 9.0 I could not recreate shared_vpc resources that I had in 8.1 version.
[Examples](https://github.com/terraform-google-modules/terraform-google-project-factory#usage), Documentation, [Upgrading guide](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/v9.0.0/docs/upgrading_to_project_factory_v9.0.md#gke-api-already-enabled) - nothing helped.
Finally, I found the solution is to use `shared_vpc` submodule, guessed by https://github.com/terraform-google-modules/terraform-google-project-factory/issues/444

Please add back shared_vpc features to root module, as it was previously or update the documentation to make it obvious for people who upgrade to 9.0 to use `//modules/shared_vpc` submodule when upgrading to 9.0 if shared_vpc networks are used.

**Comment by morgante** [comment]
@askoriy Is there a reason you can't switch to the shared_vpc submodule? I think simply documenting this is going to be a better approach.

**Comment by des-esseintes** [comment]
Faced the same issue.
What's the proper way of bringing back shared_vpcs?

**Comment by morgante** [comment]
@des-esseintes You should use the `shared_vpc` submodule.

**Comment by des-esseintes** [comment]
thanks @morgante!
hmmmm this assumes moving resources in terraform state... damn, i hate it :) was just thinking maybe there's an easier path. nevermind :)

**Comment by morgante** [comment]
@des-esseintes If you switch from the root module to the shared VPC submodule there shouldn't be any major issues as the state location is mostly the same. If you do so then share your Terraform plan I'm happy to tell you if it's a breaking change.

**Comment by des-esseintes** [comment]
it worked well, thanks!

**Comment by askoriy** [comment]
Submodule `//modules/shared_vpc` works fine if it's known that the project is _service project_ and both `shared_vpc` and `shared_vpc_subnets` variables provided with non-empty values. But it tails if one of them is empty, therefore submodule can't be used as universal project factory.

I could not reproduce errors from [this](https://github.com/terraform-google-modules/terraform-google-project-factory/pull/446#issuecomment-705607111) comment, but changes in https://github.com/terraform-google-modules/terraform-google-project-factory/pull/446 made root module works for me again for both _host_ and _service_ projects, so I created fork until fix test errors and merge that PR

**Comment by bharathkkb** [comment]
@askoriy we have an [example here](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/65534493d95c284df04d0f9c46fb39814a32b9eb/examples/shared_vpc/main.tf#L144) that tests for empty `shared_vpc_subnets` which seems to indicate it should work. I will take a look at the PR and try to narrow down the error for adding it back to root module.
