### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by amadhus** [terraform-google-modules/terraform-google-project-factory#452]
Hey Team,

I was trying to provision a GCP project using the terraform-google-project-factory module with version 8.0 and when I am trying to apply using terragrunt the changes it was throwing an error as follows:

*****************************************************
Error: Provider produced inconsistent result after apply

When applying changes to
module.project.module.project-factory.google_service_account.default_service_account,
provider "registry.terraform.io/-/google" produced an unexpected new value for
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
*****************************************************
**Note: The terragrunt plan ran successfully, showing ** resources will be provisioned or created and when I am applying the changes with terragrunt  it was throwing the above error message **

Thanks,
Madhu

**Comment by bharathkkb** [comment]
Hi @amadhus 
Could you give the following info.
- Google provider version
- Terraform version
- Example config

Additionally if you are using 2.x provider I would recommend upgrading to latest 3.x.

**Comment by bharathkkb** [comment]
x-ref https://github.com/terraform-google-modules/terraform-google-project-factory/issues/420#issuecomment-630220556

**Comment by amadhus** [comment]
Hi @bharathkkb,

Thank you very much for responding to my thread or error.

Please find the requested information below:
******************************************************
**1. Google Provider Version:** 

google  version = 3.17.0
google-beta version = 3.17.0

**2. Terraform Version:** 
Version - 0.12.25

**3. Example Config:**
We are working with the GCP Support Engineers or Experts on our initial foundation with GCP and please find the below link or URL for the code repository built and provided by the Google Team

https://github.com/k8s-labs-google/pso-western-union

**************************************************************
Please let me know if you have any questions or need more information from me?

Thanks,
Madhu

**Comment by bharathkkb** [comment]
@amadhus  Could you try bumping the provider to a more recent version of the 3.x, perhaps 3.37. We had a similar issue here: https://github.com/terraform-google-modules/terraform-google-project-factory/issues/420#issuecomment-630220556

**Comment by amadhus** [comment]
@bharathkkb, let me try that and will let you know how it goes?

**Comment by amadhus** [comment]
@bharathkkb, looks like the error was resolved when I tried to provision the project with the updated google provider version to 3.37.0.

Thank you very much for the support and patience.

**Comment by bharathkkb** [comment]
Glad to hear and thanks for the update 😄
