### ISSUE TITLE
random error when enabling apis 

### ISSUE THREAD

**Issue by antoinecastex** [terraform-google-modules/terraform-google-project-factory#461]
Hello

Just want to enable couple of apis with this sample code

resource "google_project_service" "service" {
  provider = google-beta
  for_each = toset(var.APIS)
  service            = each.key
  project            = var.PROJECT_ID
  disable_on_destroy = false
  depends_on = [
    google_project_service.service_default
  ]
}

But randomly got an error for some apis (not the same every time so it's not related to specific api)  like this

Step #1: Error: Request "Enable Project Service \"cloudscheduler.googleapis.com\" for project \"itg-hip-emea-ww-pd\"" returned error: failed to send enable services request: googleapi: Error 400: Another activation or deactivation is in progress for the following service(s): cloudscheduler.googleapis.com and project itg-hip-emea-ww-pd., failedPrecondition

Step #1: Error: Request "Enable Project Service \"redis.googleapis.com\" for project \"itg-hip-emea-ww-dv\"" returned error: failed to send enable services request: googleapi: Error 400: Another activation or deactivation is in progress for the following service(s): redis.googleapis.com and project itg-hip-emea-ww-dv., failedPrecondition

Step #1: Error: Request "Enable Project Service \"endpoints.googleapis.com\" for project \"it-selloutacd-fr-emea-dv\"" returned error: failed to send enable services request: googleapi: Error 400: Another activation or deactivation is in progress for the following service(s): endpoints.googleapis.com and project it-selloutacd-fr-emea-dv., failedPrecondition

Step #1: Error: Request "Enable Project Service \"dataflow.googleapis.com\" for project \"it-selloutacd-fr-emea-dv\"" returned error: failed to send enable services request: googleapi: Error 400: Another activation or deactivation is in progress for the following service(s): dataflow.googleapis.com and project it-selloutacd-fr-emea-dv., failedPrecondition

Step #1: Error: Request "Enable Project Service \"dataflow.googleapis.com\" for project \"it-selloutacd-fr-emea-dv\"" returned error: failed to send enable services request: googleapi: Error 400: Another activation or deactivation is in progress for the following service(s): dataflow.googleapis.com and project it-selloutacd-fr-emea-dv., failedPrecondition

Step #1: Error: Request "Enable Project Service \"stackdriver.googleapis.com\" for project \"it-onereporting-fr-emea-dv\"" returned error: failed to send enable services request: googleapi: Error 400: Another activation or deactivation is in progress for the following service(s): stackdriver.googleapis.com and project it-onereporting-fr-emea-dv., failedPrecondition

Step #1: Error: Request "Enable Project Service \"run.googleapis.com\" for project \"it-selloutdpl-fr-emea-dv\"" returned error: failed to send enable services request: googleapi: Error 400: Another activation or deactivation is in progress for the following service(s): run.googleapis.com and project it-selloutdpl-fr-emea-dv., failedPrecondition

If apis in error change every time i create a new project, that mean it's not specific api dependencies , i think it's latency general api but not sure , and how to solve that ?

thanks

**Comment by morgante** [comment]
What version of Terraform, the module, and the provider are you using? `terraform version`

**Comment by bharathkkb** [comment]
@antoinecastex Could you provide the full list of APIs you are trying to enable?
@morgante I think this is an upstream issue; ref: https://github.com/hashicorp/terraform-provider-google/issues/7103

**Comment by antoinecastex** [comment]
> What version of Terraform, the module, and the provider are you using? `terraform version`

@morgante  i'm using  beta the last one because cloud build manage everything for me :  * hashicorp/google-beta: version = "~> 3.40.0"

**Comment by antoinecastex** [comment]
> @antoinecastex Could you provide the full list of APIs you are trying to enable and provider version?
> @morgante I think this is an upstream issue; ref: [hashicorp/terraform-provider-google#7103](https://github.com/hashicorp/terraform-provider-google/issues/7103)

@bharathkkb  here is my apis 


bigquery.googleapis.com
--
storage-component.googleapis.com
cloudfunctions.googleapis.com
run.googleapis.com
datastore.googleapis.com
endpointsportal.googleapis.com
dataflow.googleapis.com
apigateway.googleapis.com
appengine.googleapis.com
sql-component.googleapis.com
redis.googleapis.com
storagetransfer.googleapis.com
iap.googleapis.com
dlp.googleapis.com
workflows.googleapis.com
sqladmin.googleapis.com
endpoints.googleapis.com
bigquerystorage.googleapis.com
storage-api.googleapis.com
sqladmin.googleapis.com
datacatalog.googleapis.com
serviceusage.googleapis.com
iamcredentials.googleapis.com
pubsub.googleapis.com
storage-component.googleapis.com
cloudbuild.googleapis.com
monitoring.googleapis.com
cloudresourcemanager.googleapis.com
clouddebugger.googleapis.com
logging.googleapis.com
monitoring.googleapis.com
cloudtrace.googleapis.com
cloudtasks.googleapis.com
cloudscheduler.googleapis.com
sourcerepo.googleapis.com
cloudkms.googleapis.com
networkmanagement.googleapis.com
iam.googleapis.com
oslogin.googleapis.com
resourceviews.googleapis.com
servicemanagement.googleapis.com
stackdriver.googleapis.com
vpcaccess.googleapis.com
container.googleapis.com
compute.googleapis.com

**Comment by antoinecastex** [comment]
@bharathkkb  any help on that please ?

**Comment by bharathkkb** [comment]
@antoinecastex Apologies for the late reply but this does seem like a provider issue. I would suggest bumping to `3.42.0` and failing that opening an issue like this https://github.com/hashicorp/terraform-provider-google/issues/7103

**Comment by antoinecastex** [comment]
hashicorp/google-beta: version = "~> 3.42.0". problem is still here @bharathkkb
