### ISSUE TITLE
Add required_providers 

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-project-factory#462]
We should add `required_providers` and lock providers to > 3.38 to prevent errors from `google_project_service_identity`.

ref: https://github.com/terraform-google-modules/terraform-google-bastion-host/pull/53, https://github.com/terraform-google-modules/terraform-google-log-export/issues/60

**Comment by thiagonache** [comment]
We'll require >= 3.39 for the default service accounts resource. Should we wait to change it at once?

**Comment by morgante** [comment]
> We'll require >= 3.47 (probably) for the default service accounts resource. Should we wait to change it at once?

Yes we can change it once as part of the next major release.

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-project-factory/pull/513/files
