### ISSUE TITLE
Rename shared_vpc

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-project-factory#463]
We could have a clearer name for the shared vpc variable [as discussed here](https://github.com/terraform-google-modules/terraform-google-project-factory/pull/459#issuecomment-702139678).

**Comment by thiagonache** [comment]
Also, we should rename shared_vpc_enabled to `enable_shared_vpc_service_project` everywhere

**Comment by thiagonache** [comment]
Let me know if I can help with it somehow.

**Comment by morgante** [comment]
For context, the only need here is to rename the submodule to something like `service_project` or `svpc_service_project` and to rename `enable_shared_vpc_service_project`.
