### ISSUE TITLE
examples/gke_shared_vpc is not valid any more

### ISSUE THREAD

**Issue by adrian-gierakowski** [terraform-google-modules/terraform-google-project-factory#471]
the code in `examples/gke_shared_vpc` does not work any more due assignment of `roles/container.hostServiceAgentUser` having been moved from `core_project_factory` to `shared_vpc_access` (#434 (f16fd05302179cd2a20485781f3f640a8d5d88ba)) 

the example should probably use `shared_vp` modules instead of top level one, or add `shared_vpc_access` (the latter approach will only be possible once #470 is merged since `shared_vpc_access` should depend on `enabled_apis` output of the service project in order to ensure appropriate creation order).

btw. the [9.0 upgrade instructions](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/docs/upgrading_to_project_factory_v9.0.md) don't make it clear enough that the top level module is not suitable anymore for creating shared vpc service projects for hosting GKE.

**Comment by davidholsgrove** [comment]
+1 The [9.0 upgrade instructions](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/docs/upgrading_to_project_factory_v9.0.md) aren't clear how to migrate from the top level module use for a project with GKE. 

Should a new module instantiation of `terraform-google-modules/project-factory/google//modules/shared_vpc_access` be included alongside the original `terraform-google-modules/project-factory/google/` to upgrade?

**Comment by morgante** [comment]
All you need to do is change which module you invoke.

```diff
module "project-factory" {
-   source  = "terraform-google-modules/project-factory/google"
+   source  = "terraform-google-modules/project-factory/google//modules/shared_vpc"
     version = "~> 9.1"
```

**Comment by davidholsgrove** [comment]
Thanks @morgante. There are a couple of vars available in the top level module which arent punched through to the `modules/shared_vpc` to pass to the `core_project_factory` which prevent this being a drop in replacement.

I've opened https://github.com/terraform-google-modules/terraform-google-project-factory/pull/476 and https://github.com/terraform-google-modules/terraform-google-project-factory/pull/477 which would be good to include if possible

**Comment by bharathkkb** [comment]
svpc has been re added to top level module by #446 and [docs](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/shared_vpc/README.md) have been created for usage of  svpc submodule.
