### ISSUE TITLE
enable_apis variable is not valid anymore in v9.1.0

### ISSUE THREAD

**Issue by raddaoui** [terraform-google-modules/terraform-google-project-factory#472]
enable_apis variable was removed in favor for activate_api_identities variable in v9.1.0 of modules/project_services so might as well remove it from list of variables, README and examples.

**Comment by morgante** [comment]
As explained in the README, `activate_api_identities` is an *addition* to the enable_apis. You can still use enable_apis.

**Comment by raddaoui** [comment]
I am referring to this 
https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/project_services/variables.tf#L21
the `enable_apis` is only present in variables and not used anywhere else in the code.

**Comment by morgante** [comment]
@raddaoui The variable is used here: https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/project_services/main.tf#L18

if you use the feature and it's not working only then should report a bug.

**Comment by raddaoui** [comment]
ok well `activate_api_identities` is used in the line you mentioned, `enable_apis` is not used anywhere in the module except the variables.tf and the README. I will leave at this since it's not a bug

**Comment by morgante** [comment]
Ah, I see the issue now. Sorry for the confusion.
