### ISSUE TITLE
Performance suffers when creating multiple projects

### ISSUE THREAD

**Issue by jwp23** [terraform-google-modules/terraform-google-project-factory#479]
It takes about 30 minutes to provision or destroy 8 projects. It looks like a lot of the action is happening with the `*.gcloud_delete.null_resource.upgrade_destroy` resources on destroy and a lot of installing gcloud for each project I create.

**Comment by morgante** [comment]
@jwp23 If you set `GCLOUD_TF_DOWNLOAD = "never"` environment variable to [false](https://github.com/terraform-google-modules/terraform-google-gcloud#downloading) then you can skip all downloads. This should speed up your deployment.

**Comment by jwp23** [comment]
Thank you. That helps a lot.
