### ISSUE TITLE
The module doesn't conform to Terraform v0.13 standards

### ISSUE THREAD

**Issue by john-welbourn-smith** [terraform-google-modules/terraform-google-project-factory#482]
This looks like it could be a very useful module but it doesn't conform to Terraform v0.13 standards.

In particular:
* Interpolation-only expressions are deprecated
* Quoted references are deprecated

Are there any plans to convert this to be v0.13 format?
I'm a bit of newbie but I'm willing to have a crack at converting it, if that will help.

**Comment by morgante** [comment]
We're happy to accept PRs for those, though do note that the module *is* compatible with Terraform 0.13 (the issues you noted are just warnings).

**Comment by john-welbourn-smith** [comment]
Thanks Morgante.
You are correct, those particular ones were just warnings but I also received a couple of errors too but they are in the gsuite_enabled module:

Error: Unsuitable value type
  on .terraform/modules/project-factory/modules/gsuite_enabled/variables.tf line 56, in variable "group_name":
  56:   description = "A group to control the project by being assigned group_role - defaults to ${project_name}-editors"
Unsuitable value: value must be known

Error: Variables not allowed
  on .terraform/modules/project-factory/modules/gsuite_enabled/variables.tf line 56, in variable "group_name":
  56:   description = "A group to control the project by being assigned group_role - defaults to ${project_name}-editors"
Variables may not be used here.

It seems Terraform v0.13 handles `descriptions` differently from earlier versions.
I'll see if I can sort those too.
