### ISSUE TITLE
failed to install provider (gsuite)

### ISSUE THREAD

**Issue by haf** [terraform-google-modules/terraform-google-project-factory#484]
```
$ tf init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/external v2.0.0
- Using previously-installed hashicorp/google v3.45.0
- Using previously-installed hashicorp/google-beta v3.45.0
- Using previously-installed hashicorp/null v2.1.2
- Using previously-installed hashicorp/random v2.3.1
- Finding hashicorp/gsuite versions matching "~> 0.1"...

Error: Failed to install provider

Error while installing hashicorp/gsuite: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/gsuite
```

I've searched the issue tracker and found only older questions about this, all related to versions of terraform and versions of this module, since upgraded. How do I initialise this module to a working state with gsuite support?

I'm following https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/gsuite_enabled/README.md (which seems to have the version wrong, too)

**Comment by bharathkkb** [comment]
@haf Since this is a 3rd party provider, I think they only recently started publishing this with Terraform 0.13. Can you try
```hcl
terraform {
  required_providers {
    gsuite = {
      source = "DeviaVir/gsuite"
      version = "0.1.54"
    }
  }
}

provider "gsuite" {
...
}
```

**Comment by haf** [comment]
That seems to work. Updated docs. Closing.
