### ISSUE TITLE
New Cloud Identity Group and Membership module

### ISSUE THREAD

**Issue by xingao267** [terraform-google-modules/terraform-google-project-factory#490]
There is a new Cloud Identity Groups API (https://gsuiteupdates.googleblog.com/2020/08/new-api-cloud-identity-groups-google.html) launched in beta recently and some TF support for it [google_cloud_identity_group](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_identity_group), [google_cloud_identity_group_membership ](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_identity_group_membership). This likely can remove the needs of using the third party gsuite provider (https://github.com/DeviaVir/terraform-provider-gsuite). We should look into this more detail, and 1) develop a module for that, and 2) migrate project factory to use that.

**Comment by xingao267** [comment]
I'm going to look into using this new API and TF resources in [Healthcare Data Protection Suite](https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite). If it hasn't been worked on, I can also upstream a new CFT module for that.

**Comment by morgante** [comment]
Thanks, a submodule and replacing the G Suite module is definitely a good idea.

**Comment by bharathkkb** [comment]
While it does increase the maintenance overhead, I think  a standalone module would help with discoverability as this is a common ask and now we have native support.

**Comment by xingao267** [comment]
Agreed. It seems a pretty common and generic use case, and a standalone module for group/membership management is also more aligned with google internal best practices imo. I can help with some maintenance work for this module.

**Comment by morgante** [comment]
Sounds good. Once you're ready to make it please just open a request (go/new-terraform-module).

**Comment by xingao267** [comment]
Created internal bug and doc for tracking. Closing this one in the project factory module.
