### ISSUE TITLE
Automatic share local providers on tests

### ISSUE THREAD

**Issue by thiagonache** [terraform-google-modules/terraform-google-project-factory#492]
Hi folks,

I know I can do it manually but I'm considering adding $HOME/.terraform.d as a shared volume when starting the tests container via the make command so I can test my own plugin.

Thoughts?

**Comment by morgante** [comment]
I don't think we should do this by default, mainly because the test environment is designed to use consistent providers for everyone.

**Comment by thiagonache** [comment]
yeah... my original idea was to add a new entry for the makefile, but I think it doesn't happen often... otherwise you guys would already have it.
