### ISSUE TITLE
Restore default_service_account = "keep" for 10.0

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-project-factory#497]
from https://github.com/terraform-google-modules/terraform-google-project-factory/pull/496#issuecomment-725341108

> 
> Testing both the current master and branch v10.0.0 I find that using `default_service_account = "keep"` consistently throws this error:
> ```
> Error: expected action to be one of [DEPRIVILEGE DELETE DISABLE], got KEEP
> 
>   on .terraform/modules/project/modules/core_project_factory/main.tf line 121, in resource "google_project_default_service_accounts" "default_service_accounts":
>  121:   action         = upper(var.default_service_account)
> 
> ```
> 
> I think you need to set `count = upper(var.default_service_accounts)=="KEEP" ? 0 : 1` on `resource "google_project_default_service_accounts" "default_service_accounts"`

**Comment by thiagonache** [comment]
@bharathkkb https://github.com/terraform-google-modules/terraform-google-project-factory/pull/498
