### ISSUE TITLE
shared_vpc module broken in 0.13

### ISSUE THREAD

**Issue by umairidris** [terraform-google-modules/terraform-google-project-factory#499]
Sample config:

```
terraform {
  required_version = ">=0.12, <0.14"
  required_providers {
    google      = "~> 3.0"
    google-beta = "~> 3.0"
  }
}

module "project" {
  source  = "terraform-google-modules/project-factory/google//modules/shared_vpc"
  version = "~> 9.2.0"

  name                    = "example-data"
  org_id                  = ""
  folder_id               = "12345678"
  billing_account         = "000-000-000"
  lien                    = true
  default_service_account = "keep"
  skip_gcloud_download    = true

  shared_vpc = "example-networks"
  activate_apis = [
    "bigquery.googleapis.com",
    "compute.googleapis.com",
    "healthcare.googleapis.com",
    "servicenetworking.googleapis.com",
    "sqladmin.googleapis.com",
  ]
}
```

Running plan or apply results in the following failure:
```
Error: the user does not have permission to access Project "example-data" or it may not exist
```

The culprit is https://github.com/terraform-google-modules/terraform-google-project-factory/blob/a3deaad77881a09e73104984124cdd0740a09e8f/modules/shared_vpc_access/main.tf#L17 caused by https://github.com/hashicorp/terraform/issues/26857.

This config will not work because the project has not yet been created, but it is doing a lookup via the data source.

Solution here would be to make the shared_vpc_access module explicitly depend on the core project factory module (tf 0.13 only), or explicitly pass dependencies down to the shared vpc access module (tf 0.12 compatible).

The terraform team also recommends NOT using data sources in the same deployment as the resource creation, so a better solution here would be to pass the project number explicitly as a var.

cc @bharathkkb

**Comment by umairidris** [comment]
I am investigating adding a module_depends_on to the module to avoid a breaking change.

**Comment by morgante** [comment]
> The terraform team also recommends NOT using data sources in the same deployment as the resource creation, so a better solution here would be to pass the project number explicitly as a var.

Could we make this an optional variable which will replace the data source if provided?
