### ISSUE TITLE
New release version

### ISSUE THREAD

**Issue by sebastianneb** [terraform-google-modules/terraform-google-project-factory#506]
We are currently using version 9.2 of the module to create projects. This version still relies on local scripts and gcloud to be available / downloadable. We would love to switch to the latest master version that doesn't need for core project components the local script part. When is a new release planned / can we trigger one? 

Appendix: We already tested with the master version that worked fine for our use-case.

**Comment by bharathkkb** [comment]
@sebastianneb we are waiting for a release of the provider with https://github.com/hashicorp/terraform-provider-google/pull/7768 and should be released soon. Closing this in favor of the thread here https://github.com/terraform-google-modules/terraform-google-project-factory/pull/496

**Comment by sebastianneb** [comment]
Thanks for the hint, wasn't aware :) Appreciate the fast answer.
