### ISSUE TITLE
Getting error with null provider configuration when trying use project factory module version 9.2.0

### ISSUE THREAD

**Issue by amadhus** [terraform-google-modules/terraform-google-project-factory#507]
Hi Team,

I am trying to use the version (9.2.0)of the project factory module for the GCP and I am getting an error when upgrading from 8.0 to 9.2.0.

**Note: If I am using or upgrading to 8.0 to 9.1.0, the pipeline is working fine as expected.**

**_**Terraform version : 0.13.4
Terragrunt version: 0.25.0**
Google provider verison: 3.49.0
Google-beta provider version: 3.49.0
null provider version: 2.1.2
random provider version: 2.2.1_**

**Please find the error message below:**

```
Error: Provider configuration not present

To work with module.project.module.project-factory.null_resource.preconditions
its original provider configuration at
provider["registry.terraform.io/-/null"] is required, but it has been removed.
This occurs when a provider configuration is removed while objects created by
that provider still exist in the state. Re-add the provider configuration to
destroy module.project.module.project-factory.null_resource.preconditions,
after which you can remove the provider configuration again.
```

Let me know if you have any questions or need more information?

Thanks,
Madhu

**Comment by bharathkkb** [comment]
Hi @amadhus 
Were you also doing a 0.12.x to 0.13 migration by chance? You may have to do a `terraform state replace-provider`. More docs here https://www.terraform.io/upgrade-guides/0-13.html#why-do-i-see-provider-during-init-

**Comment by bharathkkb** [comment]
Looks like this is indeed a 0.13 issue.The above command I suggested has been documented in this [SO](https://stackoverflow.com/questions/63590836/switch-terraform-0-12-6-to-0-13-0-gives-me-providerregistry-terraform-io-nul) post, and should also work for the google provider to solve #508.

**Comment by bharathkkb** [comment]
@amadhus was the issue resolved?
