### ISSUE TITLE
Requesting support for Terraform 0.14

### ISSUE THREAD

**Issue by craigafinch** [terraform-google-modules/terraform-google-project-factory#512]
Using Terraform 0.14.2, I get the following error message:
```
Error: Unsupported Terraform Core version

  on .terraform/modules/project-factory_project_services/modules/project_services/versions.tf line 18, in terraform:
  18:   required_version = ">=0.12.6, <0.14"

Module module.project-factory_project_services (from
terraform-google-modules/project-factory/google//modules/project_services)
does not support Terraform version 0.14.2. To proceed, either choose another
supported Terraform version or update this version constraint. Version
constraints are normally set for good reason, so updating the constraint may
lead to other errors or unexpected behavior.
```

I have to downgrade Terraform to 0.13.5 to use this module. 

It would be greatly appreciated if you could update this module to work with the latest version of Terraform. Thank you for all of the work you've already done.

**Comment by bharathkkb** [comment]
Hi @craigafinch 
We have removed the restriction on main branch. You can reference that temporarily if needed and it will be included in the `10.0` release which you can track [here](https://github.com/terraform-google-modules/terraform-google-project-factory/pull/496).
