### ISSUE TITLE
Feature Request: Service Account creation optional

### ISSUE THREAD

**Issue by sebastianneb** [terraform-google-modules/terraform-google-project-factory#526]
Hey everyone,

currently the default service account for terraform always gets created (see: [here](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/core_project_factory/main.tf#L131)). We don't really need this service account and our security team is arguing that we should not have this service account created, even it is has no rights associated with it. Since we don't want to fork this and disable the service account deletion on our own, we would love to get this in here.

I'd be very happy with issuing a Merge request here that introduces an optional flag to skip the service account creation which is per default set to `false`. 

Any options on this?

**Comment by morgante** [comment]
We'd be happy to review a flag which disables this. (`create_project_sa`, with a default of `true`)

**Comment by sebastianneb** [comment]
Happy to, thanks for the quick reply.
