### ISSUE TITLE
Module output project_id design allows to refer to non-existing (yet) gcp project

### ISSUE THREAD

**Issue by hayorov** [terraform-google-modules/terraform-google-project-factory#532]
## Problem statement
In some cases, terraform resolves module.project_id  for dependencies while real GCP project resource is not provisioned (yet).
The reason for that is lazy property/output resolution and pre-defined project_id property for google_project resources that allows terraform project_id resolution w/o resource provisioning. Project_id defined from `${var.prefix}-${var.name}`, both resources are provisioned.

## Code trace

```
output "project_id" {
  value = module.project-factory.project_id
}

output "project_id" {
  description = "Project id (depends on services)."
  value       = google_project.project.project_id
  depends_on  = [google_project_service.project_services]
}

resource "google_project" "project" {
  org_id              = local.parent_type == "organizations" ? local.parent_id : ""
  folder_id           = local.parent_type == "folders" ? local.parent_id : ""
  project_id          = "${var.prefix}-${var.name}"
  name                = "${var.prefix}-${var.name}"
  billing_account     = var.billing_account
  auto_create_network = var.auto_create_network
  labels              = var.labels
}
```

prefers to resource's property `project_id  = "${var.prefix}-${var.name}"`, both prefix and name are virtual resources or variables and have no link to the real resource.

## How to reproduce

- Depriviladge SA permissions for billing, it will trigger project billing association error later.
- Run project provisioning, get an error like:
```
2021-01-12 12:02:13  [0m[1mmodule.project.module.project-factory.null_resource.preconditions: Creation complete after 28s [id=8573291237650092838][0m[0m
2021-01-12 12:02:13  [0m[1mmodule.project.module.project-factory.google_project.main: Creating...[0m[0m
2021-01-12 12:02:14  [31m
2021-01-12 12:02:14  [1m[31mError: [0m[0m[1mfailed pre-requisites: missing permission on "billingAccounts/XXXXX-XXXX-XXXXX": billing.resourceAssociations.create[0m
2021-01-12 12:02:14  
2021-01-12 12:02:14  [0m[0m[0m
```
- tfstate fragment (issue related) - [tfstate-fragment.txt](https://github.com/terraform-google-modules/terraform-google-project-factory/files/5806353/tfstate-fragment.txt)

- Rerun provisioning (taking into account that other resources in code have project_id reference like `module.project.project_id`
- terraform resolvers module.project.project_id with that value and allows other resources provisioning with no real (physical project created)

## Workaround

- Delete module.project.module.project-factory resource that contains var.prefix data for the project_id population.

## Potential fix

Add some dependency for project-factory output `project_id` that refers to the real (calculatable) property of GCP project or/and dependant resource.

## Environment 

Terrafrom 0.13.5
module (terraform-google-modules/project-factory/google) version 9.0

**Comment by hayorov** [comment]
Heelllo...

![200](https://user-images.githubusercontent.com/991591/104836142-b22dcb00-58e6-11eb-9eb5-df751a8aa3fa.gif)

**Comment by bharathkkb** [comment]
Hi @hayorov 
Thanks for the report. We have removed the preconditions script in the 10.0 release. That should fix the error you encountered.
We do have a workaround [within project-factory](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/c41ba360a6bc6800a30d284b8fa23eb3ef5a8d7f/modules/core_project_factory/outputs.tf#L22) which waits for APIs & SVPC (if present) before project_id is resolved.

**Comment by hayorov** [comment]
Hello @bharathkkb many thanks, I'm going to update our project with v10.X and will validate the fix shortly and close the issue.

**Comment by hayorov** [comment]
FI confirm. Fixed in v10.X
