### ISSUE TITLE
Creating new host project but cannot find gcloud binary

### ISSUE THREAD

**Issue by caddac** [terraform-google-modules/terraform-google-project-factory#539]
My host project config looks like: 
```
module "host_project" {
  source                         = "terraform-google-modules/project-factory/google"
  version                        = "~> 9.2"
  name                           = var.project_id
  billing_account                = var.billing_account
  org_id                         = var.organization_id
  enable_shared_vpc_host_project = true
  folder_id                      = data.google_folder.containing_folder.id
  activate_apis                  = var.apis
}
```
I have gcloud installed and the `preconditions.py` script returns a 0 exit code. However when I plan my config, the `upgrade command` shows as 
` "upgrade_command"         = ".terraform/modules/shared.host_project.project-factory.gcloud_disable/cache/0cc0ed2b/google-cloud-sdk/bin/gcloud components update --quiet"` 
and I get an apply error saying `gcloud cannot be found`. 

Why is the upgrade command referencing the binary for gcloud at this crazy path?

**Comment by bharathkkb** [comment]
Hi @caddac 
Please use the v10 of the module which removed the gcloud dependency. Feel free to reopen if still any issue.

**Comment by caddac** [comment]
Unfortunately I'm still on terraform 12. Is using version 10 of this module an option on terraform 12?

**Comment by bharathkkb** [comment]
@caddac in that case you could fork and remove the >=0.13 restriction or you could try setting `skip_gcloud_download` in `9.2`. This should use the gcloud already in your path as opposed to downloading and installing it.
