### ISSUE TITLE
Change budget module: Accept list of project numbers instead of project ID

### ISSUE THREAD

**Issue by imrannayer** [terraform-google-modules/terraform-google-project-factory#544]
[google_billing_budget](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget) now accepts projects as projects/{project_number}. 

projects - (Optional) A set of projects of the form **projects/{project_number}**, specifying....

Can we change [budget module](https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/budget) to accept list of project numbers instead of project IDs.

Also make following change in main module:

```
module "budget" {
  source        = "./modules/budget"
  create_budget = var.budget_amount != null

  projects                         = [module.project-factory.project_number]

```

**Comment by bharathkkb** [comment]
We could keep the interface as is and use a data source to look up the project number

**Comment by morgante** [comment]
@imrannayer Are project IDs no longer accepted? I'm surprised they would do a breaking change in a minor release.

@bharathkkb Yes we should keep the interface the same.

**Comment by imrannayer** [comment]
@MajorBreakfast Code is not broken but it is picking up the difference (project ID instead of project number) and ask you to apply the update. 

```
      ~ budget_filter {
            credit_types           = []
            credit_types_treatment = "INCLUDE_ALL_CREDITS"
            labels                 = {}
          ~ projects               = [
              - "projects/1234567809",
              + "projects/prj-test-ffc8123454",
            ]
            services               = []
            subaccounts            = []
        }

```

**Comment by morgante** [comment]
Thanks, sounds like we should switch to a data source (thought this also sounds like a bug/permadiff in the provider). /cc @rileykarson

**Comment by rileykarson** [comment]
Looks like we've got https://github.com/hashicorp/terraform-provider-google/issues/8444 filed already on our side

**Comment by p3nnst8r** [comment]
Is there a way to get this in a new 9x branch (for v0.12)? This is also occurring in 9.2.0.

**Comment by morgante** [comment]
@p3nnst8r We generally don't backport fixes, though https://github.com/hashicorp/terraform-provider-google/issues/8444 should also be able to resolve this once it lands.
