### ISSUE TITLE
Impossible to use on arm64 apple M1

### ISSUE THREAD

**Issue by giulianobr** [terraform-google-modules/terraform-google-project-factory#582]
Hi there, this module is using ~> 2.1 for hashicorp/null and hashicorp/random making impossible to use on Apple M1 arch.
Are there any change to start to use the null and random 3.1, which is compatible to arm64 arch?

Thanks,

**Comment by morgante** [comment]
@giulianobr We'd be happy to review a PR which updates these versions.

**Comment by njsnx** [comment]
Submitted a PR to help with this - using this branch in a terraform workload just now and is working well @morgante
