### ISSUE TITLE
Authenticating using the content of the credentials file instead of it's path

### ISSUE THREAD

**Issue by sharkyze** [terraform-google-modules/terraform-google-project-factory#587]
Hello there,

I trying to use this module on terraform cloud which unfortunately doesn't support files. I currently have the content of the credentials file saved on terraform cloud as variable and I use it to authenticate with the google provider.

Is there any way I can authenticate in this module in the same way ?

**Comment by bharathkkb** [comment]
Hi @sharkyze 
We actually don't use `credentials_path` var anymore https://github.com/terraform-google-modules/terraform-google-project-factory/issues/523. So as long as you are authenticated with the provider, that should be sufficient for this module. Feel free to reopen if you encounter any issues on TFC.

**Comment by sharkyze** [comment]
Hey @bharathkkb, that's amazing. Thank you so much for getting back to me. I think I was mislead by the documentation.
