### ISSUE TITLE
Support Terraform 0.15 w/ version 9

### ISSUE THREAD

**Issue by haf** [terraform-google-modules/terraform-google-project-factory#591]
Hi,

It would be great if it's possible to losen the constraint <0.14 if your versions 9.x are compatible with TF 0.15?

Regards,
Henrik

**Comment by morgante** [comment]
Please upgrade to version 10.x. It is compatible with Terraform 0.15.

**Comment by haf** [comment]
Ok, it's just that there's no complete guide to do the upgrade, and as you understand this project is at the core of our deployment in GCP.
