### ISSUE TITLE
shared_vpc in submodule but svpc_host_project_id in main module for v10

### ISSUE THREAD

**Issue by haf** [terraform-google-modules/terraform-google-project-factory#592]
IMO there's an inconsistency between using the "svpc" submodule and the usage description in [the README](https://github.com/terraform-google-modules/terraform-google-project-factory#usage) — in the README you're supposed to name the property `svpc_host_project_id` but in the examples for shared vpc with service projects, that seem to do exactly (?) the same thing as the Usage in the README does, the property is named `shared_vpc` instead. Both refer to the host-project id.

https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/examples/shared_vpc/main.tf#L114

However, the upgrade docs follow the main readme https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/docs/upgrading_to_project_factory_v10.0.md#shared-vpc-host-project-variable — and therefore conflict with the only available example in the repo. So should I follow the README which is incomplete, the upgrade guide (same) or the examples that the upgrade guide refers to?

**Comment by morgante** [comment]
You should follow the upgrade guide, if you want to continue using the main (root) module.

The example is referencing a [submodule](https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/svpc_service_project) which uses a different variable name.
