### ISSUE TITLE
Using project_id output is not forcing to wait for the project creation

### ISSUE THREAD

**Issue by lsierant** [terraform-google-modules/terraform-google-project-factory#598]
Tested on `v0.13.7`, `v0.15.3`

I am using `fabric_project` submodule in a following way: 

```
terraform {
  required_version = ">= 0.13"

  required_providers {
    google      = ">= 3.71.0"
  }
}

provider "google" {
  region = "europe-central2"
}

module "fabric-project" {
  source  = "terraform-google-modules/project-factory/google//modules/fabric-project"
  version = "11.0.0"

  name            = "test-project-name-43413"
  billing_account = "<BILLING_ACCOUNT_ID>"
  parent          = "folders/<FOLDER_ID>"
  prefix          = "dev"

  auto_create_network = false

  activate_apis = [
    "compute.googleapis.com",
  ]
}

data "google_storage_project_service_account" "gcs_account" {
  project = module.fabric-project.project_id
}
```

Because `google_storage_project_service_account` datasource is depending on `project_id` from `fabric-project`, it should wait for the project creation. But running `terraform plan` is actually running datasource's GET straight away:
```
Error: Error when reading or editing GCS service account not found: googleapi: Error 400: Unknown project id: 'dev-test-project-name-43413', invalid

  on main.tf line 29, in data "google_storage_project_service_account" "gcs_account":
  29: data "google_storage_project_service_account" "gcs_account" {
```

This is because `module.fabric_project.project_id` output is using `google_project.project.project_id` attribute which is not a computed attribute, so it is available for terraform immediately, so dependencies are immediately satisfied and this is causing that other resources using `project_id` do not wait for the project creation.  

This is output definition from `fabric-project/outputs.tf`
```
output "project_id" {
  description = "Project id (depends on services)."
  value       = google_project.project.project_id
  depends_on  = [google_project_service.project_services]
}
```

Despite declared `depends_on  = [google_project_service.project_services]` the `project_id` value is available immediately. I am not sure if this is a bug in a terraform, definitely it is not really an intuitive behavior. 

Anyway the fix is trivial, just use for `project_id` output value from `id` which is in the form of `projects/<project_id>` and that forces terraform to wait for a project resource.  Tell me if it makes sense - I have a pull request ready for it. Or maybe I am missing something?
 
```
output "project_id" {
  description = "Project id (depends on services)."
  value       = trimprefix(google_project.project.id, "projects/")
  depends_on  = [google_project_service.project_services, google_project.project]
}
```

**Comment by morgante** [comment]
Please go ahead and open a pull request.
