### ISSUE TITLE
Change in behavior with svpc_host_project_id

### ISSUE THREAD

**Issue by sandy-0007** [terraform-google-modules/terraform-google-project-factory#603]
I recently got upgraded from 9.2 to 11.1 Project factory. I have been noticing some changes with the newer version.

**Prior to Upgrade:**
Although I activated dataproc and dataflow API's there wont be explicit IAM policies for service accounts (Dataproc and Dataflow) getting added to Shared VPC project.

And all the project specific service accounts were added to the Group (as there are no membership limits) which has all needed permission.

**Post Upgrade to 11.1:**
Now I'm noticing, explicit grant of IAM permission on host project (Shared VPC) and subnets for Dataproc and Dataflow.
Which I dont need it as the permissions are already applied using Groups.

**Challenge:**
I have more that 500 GCP projects and dont like to hit my IAM policy limits of 1500.

Kindly looking for your advise on how I can avoid adding such explicit permissions.

**Comment by bharathkkb** [comment]
Hi @sandy-0007 
Are you using the `svpc_service_project` [submodule](https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/svpc_service_project#shared-vpc)? If you do not want IAM management on host project you can switch to the main module.

**Comment by sandy-0007** [comment]
> M management on h

No, I'm not using `svpc_service_project` submodule.

**Comment by morgante** [comment]
@sandy-0007 Do you want to grant *any* IAM roles (for the project owner/editor group) or disable those entirely?

I think we could add a feature flag for this. Ex. `grant_shared_vpc_iam_bindings`.

**Comment by sandy-0007** [comment]
Would prefer disable as I'm updating the IAM permissions through a different terraform workspace.

My Sample code might look like which provisions the base project.

```
module "project-factory" {
  source                      = "terraform-google-modules/project-factory/google"
  version                     = "~> 11.1"
  name                        = var.project_name
  random_project_id           = "false"
  org_id                      = var.organization_id
  billing_account             = var.billing_account_id
  svpc_host_project_id        = var.vpc_project_id
  folder_id                   = var.folder_id
  shared_vpc_subnets          = ["projects/my-vpc-proj/regions/us-east1/subnetworks/sub-us-east1-x1"]
  activate_apis               = concat(module.globals.apis, ["iap.googleapis.com"])
  sa_role                     = "roles/owner"
  default_service_account     = "keep"

```

Also could you please elaborate on `grant_services_network_role`?

**Comment by morgante** [comment]
`grant_services_network_role` would be a way of disabling the IAM grants. It is not implemented yet.

Given your approach, I think a `grant_network_iam_roles` flag (defaulting to `true`) would be a reasonable addition. When `false`, none of the IAM grants for the Shared VPC would be added. We can put this on our backlog and would also be happy to review a PR.

**Comment by bharathkkb** [comment]
> No, I'm not using svpc_service_project submodule.

Apologies, forgot we added this back into root module in https://github.com/terraform-google-modules/terraform-google-project-factory/pull/446

**Comment by sandy-0007** [comment]
> `grant_services_network_role` would be a way of disabling the IAM grants. It is not implemented yet.
> 
> Given your approach, I think a `grant_network_iam_roles` flag (defaulting to `true`) would be a reasonable addition. When `false`, none of the IAM grants for the Shared VPC would be added. We can put this on our backlog and would also be happy to review a PR.

It would be awesome, if I were able to use `grant_network_iam_roles`. Let me know how soon I could leverage this flag

**Comment by sandy-0007** [comment]
Kindly let me know any approximate time frame on the availability of this flag `grant_network_iam_roles`? Because, this is becoming a blocker with our terraform upgrade to "v1.0.2" from "v0.13.5".

Thanks again!

**Comment by morgante** [comment]
@sandy-0007 It's not necessarily something we will add immediately. We can keep it in our backlog, but I can't commit to an immediate timeframe.

If you need this immediately, we would be happy to review a pull request.

Also, if you have a Google account team, feel free to ask them to raise a request internally as that will help us drive prioritization.

**Comment by sandy-0007** [comment]
Good to know, would route this request through Google account team. Appreciate your response.
