### ISSUE TITLE
Not able to create budget alert in a GCP project : 403 issue 

### ISSUE THREAD

**Issue by sowmiya-ragu** [terraform-google-modules/terraform-google-project-factory#604]
Though I have Owner permission for the service account , it is failing to create the budget alert in the project.
Even tried adding Project Billing Manager, Service usage admin roles inspite of the owner role.

Terraform code:
-------------------
provider.tf
-------------------
provider "google" {
  region = "us-west1"
  credentials = ""
  user_project_override = true
  billing_project = "project_id"
}

provider "google-beta" {
  region = "us-west1"
  credentials = ""
  user_project_override = true
  billing_project = "project_id"
}
-------------------
budget_alert.tf
-------------------

resource "google_billing_budget" "budget" {

  billing_account = "billing_account_id"
  display_name    = "Budget_alert"

  budget_filter {
    projects = ["projects/myprojectid"]
  }
  amount {
    specified_amount {
      currency_code = "USD"
      units         = "10000"
    }
  }
  threshold_rules {
    threshold_percent = 1.0
  }
  threshold_rules {
    threshold_percent = 1.0
    spend_basis       = "FORECASTED_SPEND"
  }
}
-------------------
Error:
-------------------
google_billing_budget.budget: Creating...

**_Error: Error creating Budget: googleapi: Error 403: The caller does not have permission

   in resource "google_billing_budget" "budget":
  resource "google_billing_budget" "budget" {_**

**Comment by morgante** [comment]
Where are you granting said roles?

Budgets are created on the *billing account*, not the project. Therefore you need to grant the `Billing Account Administrator` role to the service account _on the billing account_. It sounds like you're attempting to just grant permissions on the project, which is not sufficient.

**Comment by sowmiya-ragu** [comment]
Yes , I granted the permission on the project. 
But I could create budget alert in the project's billing section as shown in the attachment. Even my username is not having access as "Billing Account Administrator" to the billing account.

Is resource "google_billing_budget" , trying to create alert directly on the Billing Account itself ?
Then what terraform module should I use to create a budget alert in my project ?

<img width="825" alt="Screenshot 2021-07-08 at 11 06 41 PM" src="https://user-images.githubusercontent.com/54345307/124966863-66f8a780-e041-11eb-82e7-ba7398af5c6b.png">

**Comment by morgante** [comment]
As I already explained, there is no such thing as a budget "on a project." Budgets always exist on the billing account (and require permissions on the billing account). Even in your screenshot, you can see that you're creating the budget on the billing account.

This is explained here: https://cloud.google.com/billing/docs/how-to/budgets#create-budget

You might not have exactly the "Billing Account Administrator" role. The documentation lists other permissions/roles which could give sufficient permissions, but they are all related to the billing account.

Closing this issue.

**Comment by sowmiya-ragu** [comment]
Thanks for your help.
