### ISSUE TITLE
Not able to set data source in a list parameter in biiling_budget

### ISSUE THREAD

**Issue by sowmiya-ragu** [terraform-google-modules/terraform-google-project-factory#606]
I'm trying to access the project_id from another resource and setting in budget_filter , projects variable. As it is of list type , it takes the data value as null:

```
data "google_projects" "my-org-projects" {
  filter = "parent.id:<id> labels.business-unit:unitname"
}
locals {
    project_count = length(data.google_projects.my-org-projects.projects)
}

data "google_project" "project" {
  count = local.project_count
  project_id = data.google_projects.my-org-projects.projects[count.index].project_id
}

resource "google_billing_budget" "budget" {
  count = local.project_count
  billing_account = "00837C-63BBD1-ECBE56"
  display_name    = "${data.google_project.project[count.index].project_id}"
  budget_filter {
   **projects = ["${data.google_project.project[count.index].id}"]**
    // This throws error "Null values are not allowed for this attribute value" 
  }
  amount {
    specified_amount {
      currency_code = "USD"
      units         = "90"
    }
  }
  threshold_rules {
    threshold_percent = 0.8
}
```

How do I access the project id and set it in 
budget_filter
 {
      projects = [""]
}

?

**Comment by bharathkkb** [comment]
Hi @sowmiya-ragu 
This seems to be an issue related to the provider and not this module. Please open an issue here https://github.com/hashicorp/terraform-provider-google/issues

For quick debugging, try to output the value of `data.google_projects.my-org-projects.projects` to see if there is data being returned. I would also suggest using `for_each` on `project_id` as count will delete recreate `google_billing_budget`s when the order of the data returned changes.
