### ISSUE TITLE
Creating project in the same perimeter as the the shared vpc causes error

### ISSUE THREAD

**Issue by paolo-rm** [terraform-google-modules/terraform-google-project-factory#607]
Example:
SharedVPC Project exists in "prod" perimeter
Attaching new service project to the SharedVPC and adding it to "prod" perimeter fails with:
```
╷
│ Error: googleapi: Error 403: Request is prohibited by organization's policy. vpcServiceControlsUniqueIdentifier: HEjWQYeYynn6YJWAyVzWqA_HDyt610EZC6MIfc6cH7TpmqLl7pGDMQ, forbidden
│
│   with module.projects["project"].module.project-factory.google_compute_shared_vpc_service_project.shared_vpc_attachment[0],
│   on .terraform/modules/projects/modules/core_project_factory/main.tf line 103, in resource "google_compute_shared_vpc_service_project" "shared_vpc_attachment":
│  103: resource "google_compute_shared_vpc_service_project" "shared_vpc_attachment" {

```

Resolution would be to make the Shared VPC Attachment depends on the service control resource perimeter

**Comment by morgante** [comment]
Please provide your full configuration. We cannot help you without being able to reproduce.

**Comment by paolo-rm** [comment]
"sharedvpc-project" is the host project and it's already inside this perimeter `"accessPolicies/${var.policy}/servicePerimeters/prod_perimeter"`

I am providing project_names as a set for for_each to iterate over

```
module "projects" {
  for_each                           = var.projects
  source                             = "terraform-google-modules/project-factory/google"
  version                            = "11.0.0"
  name                               = each.key
  org_id                             = var.org_id
  billing_account                    = var.billing_account
  vpc_service_control_attach_enabled = true
  vpc_service_control_perimeter_name = "accessPolicies/${var.policy}/servicePerimeters/prod_perimeter"
  folder_id                          = google_folder.folder.id
  random_project_id                  = false
  lien                               = true
  svpc_host_project_id               = "sharedvpc-project"
  shared_vpc_subnets                 = data.google_compute_network.vpc.subnetworks_self_links
}
```

**Comment by morgante** [comment]
If you apply again, does the error go away? I haven't seen this before so want to make sure it's just a sequencing issue.

**Comment by paolo-rm** [comment]
@morgante yes on second apply it succeeds, I forked the repo locally and try to make the vpc attachment dependent on the service perimeter but didn't fix it.
Admittedly I have contributed before so I am not familiar with the intricacy of the module.
```
resource "google_compute_shared_vpc_service_project" "shared_vpc_attachment" {
  provider = google-beta

  count           = var.enable_shared_vpc_service_project ? 1 : 0
  host_project    = var.shared_vpc
  service_project = google_project.main.project_id
  depends_on      = [google_access_context_manager_service_perimeter_resource.service_perimeter_attachment[0], module.project_services]
}
```

**Comment by morgante** [comment]
@paolo-rm Based on what you've said so far, I think the dependency needs to go the other way: make the `google_access_context_manager_service_perimeter_resource.service_perimeter_attachment` dependent on the `google_compute_shared_vpc_service_project` resource. If that works for you, I'd be happy to review a PR.

**Comment by paolo-rm** [comment]
@morgante OK I am testing that, ill submit a PR if I work it out

**Comment by paolo-rm** [comment]
@morgante this is the code that actually worked in the end. Maybe I haven't explained myself clearly before but the service project needs to be in the perimeter  before it gets attached to the SharedVPC. Anyhow I have to add a `time_sleep` to make it work.
```
resource "time_sleep" "wait_30_seconds" {
  depends_on = [google_access_context_manager_service_perimeter_resource.service_perimeter_attachment[0],google_project_service.enable_access_context_manager]
  create_duration = "30s"
}

resource "google_compute_shared_vpc_service_project" "shared_vpc_attachment" {
  provider = google-beta

  count           = var.enable_shared_vpc_service_project ? 1 : 0
  host_project    = var.shared_vpc
  service_project = google_project.main.project_id
  depends_on      = [time_sleep.wait_30_seconds, module.project_services]
}
```

**Comment by paolo-rm** [comment]
I have done a manual test as well, seems to me that the VPC service control APIs is slow somehow and it takes a few seconds to respond with up-to-date infos

**Comment by paolo-rm** [comment]
it works with a `5 seconds time_sleep` 30 was just testing but it needs the time_sleep

**Comment by morgante** [comment]
We typically try to avoid explicit sleep resources, but since this API is eventually consistent we can try to use it.
