### ISSUE TITLE
Add Support for specify which APIs should be blocked by VPC Service Controls

### ISSUE THREAD

**Issue by aweberlopes** [terraform-google-modules/terraform-google-project-factory#622]
Currently there is no possibility to add details on VPC SC Perimeter they will only add in one but no services will be restricted.
Maybe it would be nice to give a list of apis that should be restricted.

**Comment by morgante** [comment]
This module just connects the project to a perimeter, it doesn't configure the perimeter itself. The restricted services are configured on the perimeter module: https://github.com/terraform-google-modules/terraform-google-vpc-service-controls.
