### ISSUE TITLE
Prevent Project service account getting added to the Shared project

### ISSUE THREAD

**Issue by sandy-0007** [terraform-google-modules/terraform-google-project-factory#630]
We don't want to the below IAM permission been getting to our Shared VPC project. I was assuming "grant_services_network_role = false" would prevent this addition but it only prevents for some of the enabled API's. 

So how do I prevent this addition?

```
  # module.project-factory.module.project-factory.google_compute_subnetwork_iam_member.service_account_role_to_vpc_subnets[0] will be created
+ resource "google_compute_subnetwork_iam_member" "service_account_role_to_vpc_subnets" {
      + etag       = (known after apply)
      + id         = (known after apply)
      + member     = "serviceAccount:project-service-account@myproject.iam.gserviceaccount.com"
      + project    = "my-shared-vpc"
      + region     = "us-west1"
      + role       = "roles/compute.networkUser"
      + subnetwork = "sub-us-west1-test"
    }
```

Terraform Code:

```
module "project-factory" {
  source                      = "terraform-google-modules/project-factory/google"
  version                     = "~> 11.2.2"
  name                        = var.project_name
  random_project_id           = "false"
  org_id                      = var.organization_id
  billing_account             = var.billing_account_id
  svpc_host_project_id        = var.vpc_project_id
  folder_id                   = var.folder_id
  shared_vpc_subnets          = var.shared_vpcs
  grant_services_network_role = false
  activate_apis               = module.apis_list.apis
  sa_role                     = var.sa_role
  default_service_account     = "disable"
  disable_services_on_destroy = "false"
}
```

**Comment by morgante** [comment]
@sandy-0007 Based on [this comment](https://github.com/terraform-google-modules/terraform-google-project-factory/pull/618#issuecomment-926846678), my understanding was that you had what you needed.

Can you clarify what has changed? Did you not validate the prior PR or was this a regression?

**Comment by bharathkkb** [comment]
@sandy-0007 In this case the permissions are being granted to the [project-factory SA ](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/1867fafc0f038c38f8b82ae380f66adccf9b8759/variables.tf#L80). `grant_services_network_role` currently only prevents networks roles being granted on API SAs per https://github.com/terraform-google-modules/terraform-google-project-factory/issues/603.  If you set `create_project_sa` to false this SA will no longer be created.

**Comment by bharathkkb** [comment]
@sandy-0007 thanks for clarifying. This was existing behavior in [9.2](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/65534493d95c284df04d0f9c46fb39814a32b9eb/modules/core_project_factory/main.tf#L272-L275) and should not create a diff if you are upgrading per #603. We can however use the new `grant_services_network_role` to control this as well. Would that work for you?

**Comment by sandy-0007** [comment]
Yes @bharathkkb, that would be great, if you can add this option part of `grant_services_network_role` or something like that.

**Comment by eahrend** [comment]
I'm running into this issue as well, is there any current workaround?

**Comment by morgante** [comment]
If you want to manage IAM elsewhere, you can skip the SA creation with `create_project_sa = false`.

**Comment by sandy-0007** [comment]
Yes, that worked. Thank you. This issue can be closed.
