### ISSUE TITLE
Allow configuring default network service tier for projects

### ISSUE THREAD

**Issue by jawnsy** [terraform-google-modules/terraform-google-project-factory#639]
### TL;DR

This proposes the addition of a setting to configure the default [Network Service Tier](https://cloud.google.com/network-tiers) for projects.

### Terraform Resources

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_project_default_network_tier

### Detailed design

Add a `network_tier` field for the project and configure it. The default value should be `PREMIUM`, which is the default on Google Cloud.

**Comment by morgante** [comment]
This seems like a reasonable addition, we'd be happy to review a pull request adding it.
