### ISSUE TITLE
Incorrect state with API Activations

### ISSUE THREAD

**Issue by LusciousPear** [terraform-google-modules/terraform-google-project-factory#65]
We were ironing out some permission issues so needed to re-run a TF pipeline a few times. It appears possible to create a project, fail to activate the right APIs, and then cause other parts of the pipeline to fail.  (Note: the module name is our internal fork of project factory with no changes).

To reproduce, try to create a new project using a Service Account lacking this permission: 

``` module.project-factory-project.module.sfdc_project.data.google_organization.org: data.google_organization.org: Error reading Organization Not Found : organizations/849937818733: googleapi: Error 403: The caller does not have permission, forbidden```

If you fix that, then you will get this error:

```
Error: Error refreshing state: 1 error(s) occurred:
 * module.project-factory-project.module.sfdc_project.data.google_compute_default_service_account.default: 1 error(s) occurred:
 * module.project-factory-project.module.sfdc_project.data.google_compute_default_service_account.default: data.google_compute_default_service_account.default: Error reading GCE service account not found: googleapi: Error 403: Project 722914074885 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=722914074885 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
```

All subsequent plans will fail because this call happens early in the plan, preventing the rest.

**Comment by morgante** [comment]
Do you know what permission you were missing?

This unfortunately is a hard issue to resolve due to how Terraform works, but https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/docs/TROUBLESHOOTING.md#unable-to-query-status-of-default-gce-service-account should address that.

@adrienthebo One though, could we also see if running `terraform plan -refresh=false` lets you work through the state deadlock.

**Comment by adrienthebo** [comment]
A quick inspection of the error message indicates that the service account may have not had the `resourcemanager.organizations.get` permission, typically granted through `roles/resourcemanager.organizationViewer`. I believe that https://github.com/terraform-google-modules/terraform-google-project-factory/pull/21 allows users to bypass that requirement by directly providing the organization ID - when you invoked Terraform with the project-factory did you set the `org_id` variable?

@morgante will do - I'll make a note to test that path.

**Comment by LusciousPear** [comment]
Thank you for your quick replies. Yes, we set the org_id variable. Also, we do have `roles/resourcemanager.organizationViewer` explicitly enabled on the Service Account which has the creds Project Factory uses to create these projects.

**Comment by carlodicelico** [comment]
FWIW, and not entirely sure whether or not this is helpful info, but I have seen this issue too. For now, I had to comment out the `null_resource` that removes default service accounts. I just remove the SAs manually.

**Comment by morgante** [comment]
Do you think you could share the full IAM roles info on one of the projects where you saw this issue? (Feel free to send privately: morgantep@google.com)
