### ISSUE TITLE
Support M1 Macs

### ISSUE THREAD

**Issue by ScottPierce** [terraform-google-modules/terraform-google-project-factory#669]
### TL;DR

M1 Macs can't use this package as you get the error
```
Provider registry.terraform.io/hashicorp/random v2.3.1 does not have a package available for your current platform, darwin_arm64.
```

I assume updating to the latest random package from hashicorp will fix this.

### Terraform Configuration

```hcl
NA
```

### Terraform Version

```sh
Terraform v1.1.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/github v4.17.0
+ provider registry.terraform.io/hashicorp/google v3.90.1
+ provider registry.terraform.io/hashicorp/google-beta v3.90.1
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/integrations/github v4.4.0
```

**Comment by bharathkkb** [comment]
@ScottPierce thanks for the report! I believe `3.1.0`+ of random provider should support this and we have removed our constraints to support this in https://github.com/terraform-google-modules/terraform-google-project-factory/pull/583. 

Could you try the latest release v11.3.0 of project factory or if its still failing provide an example configuration.?

**Comment by ScottPierce** [comment]
That seems to have worked. Thanks!
