### ISSUE TITLE
export bucket_name in output

### ISSUE THREAD

**Issue by leeyc0** [terraform-google-modules/terraform-google-project-factory#674]
### TL;DR

Module output should export bucket_name too, to make further operations on the created bucket easier. (For example, bucket IAM configurations.) Without exporting bucket_name, operations that depends on the created bucket will either need a `trimprefix(module.project-factory.project_bucket_url[0], "gs://")` in bucket_name argument or a `depend_on` explicitly.

**Comment by morgante** [comment]
We would probably just output the entire bucket resource.

Since this has an easy workaround, marking this as P4. We would be happy to review a PR though.
