### ISSUE TITLE
Should not point to master of external CFT module during testing

### ISSUE THREAD

**Issue by tpdownes** [terraform-google-modules/terraform-google-project-factory#685]
### TL;DR

#627 allowed one of the tests to point to the HEAD `master` for the `terraform-google-vpc-service-controls` module; I believe the issue was to allow for 4.x providers. Once a released version of `terraform-google-vpc-service-controls` supports 4.x, we should adopt it.

### Terraform Configuration

https://github.com/terraform-google-modules/terraform-google-project-factory/blob/44a9feca98daf719f091fb8eeac2cc9e292cfc0d/test/fixtures/vpc_sc_project/main.tf#L22

### Terraform Version

```sh
Terraform v1.1.5
on darwin_amd64
```

**Comment by apeabody** [comment]
Fix in #693
