### ISSUE TITLE
Check project before making it

### ISSUE THREAD

**Issue by laithrafid** [terraform-google-modules/terraform-google-project-factory#702]
### TL;DR

project factory needs to check existing projects before trying to recreate , when there's an error in apply process and rerun `terraform apply` , it would through error below : 
to workaround this , you have `terraform destroy` then `terraform apply`

```
╷
│ Error: error creating project kubernetes-cluster-c686 (kubernetes-cluster): googleapi: Error 409: Requested entity already exists, alreadyExists. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission
│
│   with module.project_config.module.project-factory.google_project.main,
│   on .terraform/modules/project_config/modules/core_project_factory/main.tf line 65, in resource "google_project" "main":
│   65: resource "google_project" "main" {
│
╵
___________________________________________________________
```

### Terraform Resources

```markdown
first, i think this needs to check list of project and name before trying to recreate project name
```

**Comment by bharathkkb** [comment]
Thanks for the feedback @laithrafid 
Unfortunately this is not something we can do within the module. Please open an issue in the provider repo for trying to catch this at plan time https://github.com/hashicorp/terraform-provider-google/issues
