### ISSUE TITLE
Moving ISTIO to ASM on safer-cluster-update-variant gke cluster 

### ISSUE THREAD

**Issue by yugandhar-btc** [terraform-google-modules/terraform-google-project-factory#727]
### TL;DR

Google is recommend to migrate **istio** service mesh to **Anthos Service mesh**  before kubernetes version v1.25 .

reference modules path:-
[gke_clusters](https://github.com/GoogleCloudPlatform/solution-acceleration-toolkit/blob/master/templates/tfengine/components/resources/gke_clusters)

Cloud you please help us. __

### Terraform Resources

```markdown
#terraform0.14.0
```

**Comment by bharathkkb** [comment]
@yugandhar-btc you can use the ASM module here https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/asm
