### ISSUE TITLE
[Doubt] This is a temporary issue. Is there any risk to use this module in a production account?

### ISSUE THREAD

**Issue by fabio-filho** [terraform-google-modules/terraform-google-project-factory#730]
Hi, I doubt the use of this module. 
I'm sorry if this is not the appropriate channel. I'm not sure if there is a risk of connecting this module to my production account.

I tried to use my account for testing purposes but I'm stuck here:
```
╷
│ Error: error creating project tf--pareto-ads--prod-fb1f (tf--pareto-ads--prod): googleapi: Error 403: The caller does not have permission, forbidden. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission
│ 
│   with module.project-factory.module.project-factory.google_project.main,
│   on .terraform/modules/project-factory/modules/core_project_factory/main.tf line 65, in resource "google_project" "main":
│   65: resource "google_project" "main" {
│ 
╵
```

**Comment by bharathkkb** [comment]
@fabio-filho This is safe to use in production. You will need the project creator permissions to create new projects. You can see the requirements in https://github.com/terraform-google-modules/terraform-google-project-factory#permissions
