### ISSUE TITLE
terraform-google-modules/project-factory/google v10.1 generating Error: Unsupported argument

### ISSUE THREAD

**Issue by mshryr** [terraform-google-modules/terraform-google-project-factory#743]
We have been using version 10.1 with the impersonate_service_account and yesterday we noticed that the code stopped working for deployed projects complaining of Error: Unsupported argument for the impersonate_service_account field. I am aware that the module is on v13 right now but it is not clear why the older module should stop working.

**Comment by bharathkkb** [comment]
Hi @mshryr 
Thanks for the report! Were you by chance pinned to the minor version using pessimistic constraint operator? Could you check if the downloaded module was indeed 10.1 or one of the other minor versions?

**Comment by mshryr** [comment]
It seems like it was downloading 10.4.0 of the project factory module. You might be right. Is there a reason why it would do that and not go for the intended 10.1 version as defined in the module?

Step #1 - "tf plan validate all": Downloading terraform-google-modules/project-factory/google 10.4.0 for project-factory-host-compute-engine...
Step #1 - "tf plan validate all": - project-factory-host-compute-engine in .terraform/modules/project-factory-host-compute-engine
Step #1 - "tf plan validate all": - project-factory-host-compute-engine.budget in .terraform/modules/project-factory-host-compute-engine/modules/budget
Step #1 - "tf plan validate all": - project-factory-host-compute-engine.gsuite_group in .terraform/modules/project-factory-host-compute-engine/modules/gsuite_group
Step #1 - "tf plan validate all": - project-factory-host-compute-engine.project-factory in .terraform/modules/project-factory-host-compute-engine/modules/core_project_factory
Step #1 - "tf plan validate all": - project-factory-host-compute-engine.project-factory.project_services in .terraform/modules/project-factory-host-compute-engine/modules/project_services
Step #1 - "tf plan validate all": - project-factory-host-compute-engine.quotas in .terraform/modules/project-factory-host-compute-engine/modules/quota_manager
Step #1 - "tf plan validate all": - project-factory-host-compute-engine.shared_vpc_access in .terraform/modules/project-factory-host-compute-engine/modules/shared_vpc_access
Step #1 - "tf plan validate all": Downloading terraform-google-modules/project-factory/google 10.4.0 for project-factory-messaging-servers...
Step #1 - "tf plan validate all": - project-factory-messaging-servers in .terraform/modules/project-factory-messaging-servers
Step #1 - "tf plan validate all": - project-factory-messaging-servers.budget in .terraform/modules/project-factory-messaging-servers/modules/budget
Step #1 - "tf plan validate all": - project-factory-messaging-servers.gsuite_group in .terraform/modules/project-factory-messaging-servers/modules/gsuite_group
Step #1 - "tf plan validate all": - project-factory-messaging-servers.project-factory in .terraform/modules/project-factory-messaging-servers/modules/core_project_factory
Step #1 - "tf plan validate all": - project-factory-messaging-servers.project-factory.project_services in .terraform/modules/project-factory-messaging-servers/modules/project_services
Step #1 - "tf plan validate all": - project-factory-messaging-servers.quotas in .terraform/modules/project-factory-messaging-servers/modules/quota_manager
Step #1 - "tf plan validate all": - project-factory-messaging-servers.shared_vpc_access in .terraform/modules/project-factory-messaging-servers/modules/shared_vpc_access

**Comment by bharathkkb** [comment]
@mshryr it turned out to be an issue on our side. I have fixed the release now. You can also pin explicitly to a patch version like `= "10.3.0"` to workaround this.
