### ISSUE TITLE
module initialization issue

### ISSUE THREAD

**Issue by parmarsumit** [terraform-google-modules/terraform-google-project-factory#78]
Initializing modules...
- module.project-factory
  Found version 0.2.1 of terraform-google-modules/project-factory/google on registry.terraform.io
  Getting source "terraform-google-modules/project-factory/google"

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Provider "gsuite" not available for installation.

A provider named "gsuite" could not be found in the official repository.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

**Comment by aaron-lane** [comment]
Hi @parmarsumit. Thank you for your interest in the project!

I apologize for the trouble. This should be fixed by #77.

**Comment by fergyCR** [comment]
Thank you! I was having the same issue.

**Comment by aaron-lane** [comment]
#77 was merged.
