### ISSUE TITLE
converge vpc-sc-project-local test is suddently failing due to lack of project_id

### ISSUE THREAD

**Issue by apeabody** [terraform-google-modules/terraform-google-project-factory#780]
### TL;DR

Config: https://github.com/terraform-google-modules/terraform-google-project-factory/blob/7a40ef284c070dcff4c92d75dba8e31a1b88dcec/build/int.cloudbuild.yaml#L130

Example: https://pantheon.corp.google.com/cloud-build/builds/2cf64e84-f62f-4c99-a0b1-205af7bbd058;step=21?project=cloud-foundation-cicd

### Terraform Configuration

```hcl
CI
```

### Terraform Version

```sh
CI
```

**Comment by bharathkkb** [comment]
It might have been https://github.com/terraform-google-modules/terraform-google-vpc-service-controls/issues/103
