### ISSUE TITLE
Add grants for datastream apis in shared_vpc_access module

### ISSUE THREAD

**Issue by imrannayer** [terraform-google-modules/terraform-google-project-factory#787]
### TL;DR

`roles/compute.networkAdmin role` granted to Datastream's service account `service-[project_number]@gcp-sa-datastream.iam.gserviceaccount.com` for datastream connectivity configuration on shared VPC host project. See the details [here](https://cloud.google.com/datastream/docs/create-a-private-connectivity-configuration)

**Comment by dtsong** [comment]
I think we need to set this to default to `true` per the documentation: https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/shared_vpc_access/variables.tf#L65

Docs: https://cloud.google.com/datastream/docs/create-a-private-connectivity-configuration
