### ISSUE TITLE
make org id optional

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-project-factory#808]
### TL;DR

Org id could be made optional when folder is used.

**Comment by oliverboehme-ida** [comment]
From what I see [here](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/core_project_factory/main.tf#L38-L39), `folder_id` is already preferred if both `folder_id` and `org_id` are given.

Only thing that is missing is a `default` on `org_id` so it would be optional.
And maybe some smart check that one of both variables has to be set, anything else?

**Comment by bharathkkb** [comment]
It is preferred but currently the input var is a required which we could make optional
https://github.com/terraform-google-modules/terraform-google-project-factory/blob/6b0412e61a564477128a3fd2e0735e00aae5e572/variables.tf#L29-L32
