### ISSUE TITLE
Deprecation warning for "app_engine"

### ISSUE THREAD

**Issue by mikeraimondi** [terraform-google-modules/terraform-google-project-factory#81]
Using v0.21 of this module and v1.19.1 of `terraform-provider-google`, we see the following warning:

`Warning: module.priv-env.module.vault-project.google_project.project: "app_engine": [DEPRECATED] Use the google_app_engine_application resource instead.`

**Comment by nstogner** [comment]
Looking to fix with:

https://github.com/terraform-google-modules/terraform-google-project-factory/pull/134

**Comment by lawliet89** [comment]
In the mean time, if you don't use appengine, you can just apply this [commit](https://github.com/basisai/terraform-google-project-factory/commit/616735e19ded0098ae62c1384143e4e7cff4bbed) to your copy or the module or the linked fork to simply remove `app_engine`.

**Comment by aaron-lane** [comment]
Fixed by #144.
