### ISSUE TITLE
Support v5 google provider version

### ISSUE THREAD

**Issue by gszzzzzz** [terraform-google-modules/terraform-google-project-factory#841]
### TL;DR

[v5 version of `google` provider](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.0.0) just released. This module should support this version too.

### Terraform Resources

- [Related Release Note](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.0.0)

**Comment by oliverboehme-ida** [comment]
Solved by #843 ?
