### ISSUE TITLE
How do I use lien_reason?

### ISSUE THREAD

**Issue by red8888** [terraform-google-modules/terraform-google-project-factory#882]
### TL;DR

Whats the deal with this, I want to use this: https://github.com/terraform-google-modules/terraform-google-project-factory/blob/37cda99f07809f75b7a1ab2128ad21521d45c805/modules/fabric-project/variables.tf#L62

I'm on the latest version of the module and all I have is `lien`. I want to add a lien description with the module.

Does the module add a description for me? Should I not be adding my own description?

### Terraform Resources

```markdown
terraform-google-project-factory
```

**Comment by imrannayer** [comment]
@red8888 from description of the variables in module and provider

```
variable "lien_reason" {
  description = "If non-empty, creates a project lien with this description."
}
```


From provider description

[reason](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/resource_manager_lien#reason) - (Required) Concise user-visible strings indicating why an action cannot be performed on a resource. Maximum length of 200 characters.
