### ISSUE TITLE
Please add parent_folder to the output. 

### ISSUE THREAD

**Issue by davidlbyrne** [terraform-google-modules/terraform-google-project-factory#886]
### TL;DR

It seems like this module is lacking in outputs. Considering it creates over 50 resources and only surfaces 15 outputs. Could you please surface parent_folder in the outputs. I'm wrapping this module and would like to write some unit test but I'm held back by what is surfaced in the outputs because I can't references the underlining resources. 

### Terraform Resources

```markdown
All of the possible attributes and arguments from the google_project resource.
```

### Additional information

It would be very helpful, Thank you.

**Comment by imrannayer** [comment]
@davidlbyrne parent_folder is an input for the module. Can u use that for your test?
