### ISSUE TITLE
Support GCP and GCP-Beta Provider Versions ~>5.0

### ISSUE THREAD

**Issue by cherusk** [terraform-google-modules/terraform-google-project-factory#887]
### TL;DR

Currently, the module constraints both google provider versions to ~> 4.11

We want to use the module with higher Provider Versions ~>5.0

**Comment by imrannayer** [comment]
@cherusk I cant find any limitation ~> 4.11. Can you plz post the file where you see it?

**Comment by cherusk** [comment]
Hi @imrannayer  thanks for reaching out.

https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/README.md

That is even stated in your Readme -> "Software Requirements".

Viably that constraint is stemming from modules this one is depending on.

**Comment by imrannayer** [comment]
Thats incorrect in readme only. In module we are suing >= everywhere (check version.tf files). 5.X provider version not restricted in module, you can use it.
