### ISSUE TITLE
Ignore firebase service label

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-google-project-factory#930]
### TL;DR

Firebase automatically adds a label which we should ignore as part of project creation

https://firebase.google.com/support/faq#project-label-firebase-enabled

**Comment by Bradley-McCallion** [comment]
Why was this done? I've been trying to create a Firebase project on an existing GCP project via Terraform but this means it can't be done. What is the logic behind ignoring this? See official tutorial here: https://firebase.google.com/codelabs/firebase-terraform#3
