### ISSUE TITLE
Shared VPC granting is broken

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-project-factory#97]
In #72, we messed up the logic for granting networkUser permission.

There are meant to be 3 different conditions.

1. No `shared_vpc` and no subnets => no grants
2. `shared_vpc` and no subnets => grant to the project (all networks/subnets)
3. `shared_vpc` and subnets => grant to the subnets (and not to the project)

**Comment by leone145** [comment]
I have verified on our end that the fix listed does correct the condition of not adding the group_name to the project level if condition 3 is met. However group_name does not get cleaned up from the shared subnet on project destroy.

**Comment by aaron-lane** [comment]
Fixed by #164.
